deploy/kubernetes/helm/che/templates/dashboard-ingress.yaml, deploy/kubernetes/helm/che/values.yaml
Expose dashboard ingress path. By default it is set to `/dashboard'.
To override a default value pls use `--helm-patch-yaml` flag with `chectl`:
```bash
cat >patch.yaml<<EOF
> dashboard:
>   ingressPath: /dashboard/*
> EOF
chectl server:deploy --installer=helm < .... >  --helm-patch-yaml patch.yaml
```
N/A
https://github.com/eclipse/che/issues/19914
1. `cd deploy/kubernetes/helm/che`
2. `helm dependency update`
3. `chectl server:deploy --installer=helm --platform=minikube  --multiuser  --templates ../../..`
4. `chectl dashboard:open` check if dashboard is opened in a browser
Reviewers, …
=> chore: Expose dashboard ingress path

multiuser/keycloak/che-multiuser-keycloak-user-remover/pom.xml, multiuser/keycloak/che-multiuser-keycloak-user-remover/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakPasswordGrantTokenRequester.java, multiuser/keycloak/che-multiuser-keycloak-user-remover/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserRemover.java, multiuser/keycloak/che-multiuser-keycloak-user-remover/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakPasswordGrantTokenRequesterTest.java, multiuser/keycloak/che-multiuser-keycloak-user-remover/src/test/java/org/eclipse/che/multiuser/keycloak/server/KeycloakUserRemoverTest.java
Signed-off-by: David Kwon <dakwon@redhat.com>
This PR allows users to be deleted from the Che Postgres database in the case where the user does not exist in the Keycloak level.
A warning message is logged when this happens, e.g.
```
[WARN ] [.e.c.m.k.s.KeycloakUserRemover 113]  - User with userId: 57453ea8-f076-48ea-8636-4009c8adc283 does not exist in Keycloak. Continuing user deletion.
```
Image: `quay.io/dkwon17/che-server:che-19473`
1. Create a new user from Keycloak and login to Che so that the user exists in the Keycloak and the Che Postgres side.
2. Manually delete the user from Keycloak so that the user exists in the Che Postgres side, but not on the Keycloak side.
3. Delete the user using the user deletion endpoint. This results in a 204 response. The user is now deleted on the …
=> fix: Continue user deletion if user cannot be found in KeyCloak

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryLinksHelper.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryLinksHelperTest.java
Backport of: https://github.com/eclipse-che/che-server/pull/33
Prevent relative files (like che-editor.yaml, extensions.json) links creation for DEvfile v.2 factories from raw URL-s;
Fixes eclipse/che#19985
Accept factory from devfile v.2 located at some non-repository URL (e.g. gist or equal). There must be no links to the related files (like che-editor.yaml, extensions.json)
=> fix: Do not generate relative files links if factory source is a raw URL

wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
Fixes the GitLab file reading behavior, by omitting `master` branch name by default.
Before PR: Accepting factory with GitLab repository, having default branch other than 'master' is failing;
After PR: Accepting factory with GitLab repository, having default branch other than 'master' is OK;
=> fix: Omit default branch for GitLab repositories as it is not always 'master'

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMerger.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/PodMergerTest.java
Adds a check to ensure that the same toleration does not get added multiple times to workspace pods.
Issue  eclipse/che#19975
- Tested on AKS (but should apply to any Kubernetes platform)
- Installation method: Helm
- In values,yaml, set the che.cheWorkspacePodTolerations
- Launch a workspace and use 'kubectl get pod' to confirm that each toleration only appears once.
=> fix: prevent duplicate tolerations on workspace pods

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java
Curerntly, in case of any failure during retrieval of the file from public repository, we're starting OAuth procedure even if the reposiitory is public and no OAuth is configured on server.  (for example, no SSL key refistered or server unavailable w\out VPN or other kind of error.) In that case user will see a unexpeced error messages saying Oauth tokens is not resolvable etc.
This PR adds property which exlplicitly indicates that Gitlab OAuth is ON or OFF, so we can know should we start authentication or no.
https://github.com/eclipse/che/issues/19991 (partially)
Run a factory for examle pointing to RH internal CEE without VPN connected:
( URL example: https://gitlab.cee.redhat.com/rhopp/che-server/-/tree/main)
Error before:
Error after:
Docs PR: …
=> fix: Explicit configuration for GitLab OAuth integration

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelper.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/NodeSelectorProvisioner.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/TolerationsProvisioner.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/PVCSubPathHelperTest.java
Speed up workspace creation / start operations when using nodeSelectors (and tolerations).
This changes the behaviour of the pods spawned by `org.eclipse.che.workspace.infrastructure.kubernetes.namespace.pvc.PVCSubPathHelper` to add the same nodeSelectors and tolerations as the workspace pods. This avoids those pods encountering Multi-Attach errors when attaching the PVC used by persistent workspaces, which greatly speeds up workspace startup.
Fixes eclipse/che#19990
1. In values.yaml, specify a nodeSelector (and optionally, tolerations) for the workspace pods:
```yaml
che:
workspace:
podNodeSelector: "node.label=che-workspaces"
```
2. Launch Che on Kubernetes (in our case, AKS)
3. Log in to Che and launch a workspace with persistence enabled
4. In the user's namespace, observe the pods …
=> fix: Add nodeSelectors and tolerations to utils pods

make-release.sh
Change commit message in release workflow to comply with semantic pr/commit rules
N / A
N / A
=> ci: Use semantic commit message in release workflow

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
To be able to create edit and delete namespaced secretes workspace user needs special permissions. This PR adds a kubernetes role for secrets, and binds it to a workspace user.
https://github.com/eclipse/che/issues/19837
1. Start a workspace and open a terminal from ide container
2. Send an HTTP request to kubernetes API to create a secret: `curl -X POST <kubernetes API url>/api/v1/namespaces/<namespace name>/secrets --header "Content-Type: application/json" -d '{ "apiVersion": "v1", "kind": "Secret", "metadata": { "name" : "new-secret" } }' `
Reviewers, please comment how you tested the …
=> Add an ability to create and edit namespaced secrets by workspace user

infrastructures/kubernetes/pom.xml, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/DirectKubernetesAPIAccessHelperTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/TraefikGatewayRouteConfigGeneratorTest.java
At this point tests from infrastructure-kubernetes are not executed due to dependency conflict
```
DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=20408, ConflictMarker.markTime=15531, ConflictMarker.nodeCount=1, ConflictIdSorter.graphTime=2047, ConflictIdSorter.topsortTime=5830, ConflictIdSorter.conflictIdCount=0, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=10009, ConflictResolver.conflictItemCount=0, DefaultDependencyCollector.collectTime=3812, DefaultDependencyCollector.transformTime=65518}
[DEBUG] Test dependencies contain org.junit.jupiter:junit-jupiter-api. Resolving org.junit.jupiter:junit-jupiter-engine:5.7.2
[DEBUG] Resolving artifact org.junit.jupiter:junit-jupiter-engine:5.7.2
[DEBUG] Resolved artifact …
```
=> Fix: Enable infrastructure-kubernetes tests

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Revert the kubernetes Secrets role due to the security vulnerability
see https://github.com/eclipse-che/che-server/pull/44
https://github.com/eclipse/che/issues/19837
=> fix: Revert the kubernetes Secrets role due to the security vulnerability

infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/multiuser/oauth/KubernetesOidcProviderConfigFactoryTest.java
Signed-off-by: Michal Vala <mvala@redhat.com>
fix flaky test at KubernetesOidcProviderConfigFactoryTest. 
One tests requires set the `EnvironmentContext` and second test require it to be empty (or at least no token in the subject). There was no cleanup so when they run in inverse order, `EnvironmentContext` was still set from 1st test.
CI
=> test: fix flaky test KubernetesOidcProviderConfigFactoryTest

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties, assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties, deploy/kubernetes/helm/che/templates/configmap.yaml, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesCheApiExternalEnvVarProvider.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/KubernetesCheApiInternalEnvVarProvider.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/KubernetesBrokerEnvironmentFactory.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/wsplugins/brokerphases/OpenshiftBrokerEnvironmentFactory.java, multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakJwkProvider.java, multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakProfileRetriever.java, multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfo.java, multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java, multiuser/keycloak/che-multiuser-keycloak-server/src/test/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProviderTest.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/spi/provision/env/CheApiEnvVarProvider.java
If internal links are not specified, the external one should be used
https://github.com/eclipse/che/issues/18643
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
=> fix: If internal links are not specified, the external one should be used

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/KubernetesNamespaceService.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/api/server/KubernetesNamespaceServiceTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
REST Service on the Che server-side that will initiate k8s namespace provisioning
Fixes https://github.com/eclipse/che/issues/20165
1.  Build che-server image or deploy `quay.io/skabashn/che-server:che20165`
2. Run 
```
curl -X POST 'https://che-eclipse-che.appsXXXXXX.opentlc.com/api/kubernetes/namespace/provision' \
-H 'Connection: keep-alive' \
-H 'Pragma: no-cache' \
-H 'Cache-Control: no-cache' \
-H 'sec-ch-ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Authorization: Bearer eyJhbGcXXXXXX' \
-H 'sec-ch-ua-mobile: ?0' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36' \
-H 'Sec-Fetch-Site: same-origin' \
-H …
```
=> feat: REST Service on the Che server-side that will initiate k8s namespace provisioning

deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/templates/ingress.yaml, deploy/kubernetes/helm/che/custom-charts/che-jaeger/templates/ingress.yaml, deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/endpoints-monitor-rolebinding.yaml, deploy/kubernetes/helm/che/custom-charts/che-keycloak/templates/ingress.yaml, deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/templates/ingress.yaml, deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml, deploy/kubernetes/helm/che/templates/dashboard-ingress.yaml, deploy/kubernetes/helm/che/templates/exec-role.yaml, deploy/kubernetes/helm/che/templates/ingress.yaml, deploy/kubernetes/helm/che/templates/metrics-ingress.yaml, deploy/kubernetes/helm/che/templates/resource-monitor-role-binding.yaml, deploy/kubernetes/helm/che/templates/resource-monitor-role.yaml, deploy/kubernetes/helm/che/templates/workspace-exec-role-binding.yaml, deploy/kubernetes/helm/che/templates/workspace-view-role-binding.yaml, deploy/kubernetes/helm/che/templates/workspace-view-role.yaml, deploy/kubernetes/helm/che/tiller-rbac.yaml
Use `rbac.authorization.k8s.io/v1` and `networking.k8s.io/v1` API since  `rbac.authorization.k8s.io/v1beta` and `extensions/v1beta1` won't be available in kubernetes v1.22
See deprecation guide https://kubernetes.io/docs/reference/using-api/deprecation-guide/
N/A
https://github.com/eclipse/che/issues/20182
1. start minikube
2. `cd <PATH_TO_PROJECT>deploy/kubernetes/helm/che && helm dependency update`
2. `chectl server:deploy --installer=helm --platform=minikube   --multiuser --domain=$(minikube ip).nip.io   --templates <PATH_TO_PROJECT>/deploy`
Reviewers, please comment how you tested …
=> chore: use rbac.authorization.k8s.io/v1 and networking.k8s.io/v1 API

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccountTest.java
Workspace namespace is not prepared properly and startup is broken  if `metrics.k8s.io` API is not enabled on the cluster or Che SA cannot create appropriate roles due to lack of permissions.
https://issues.redhat.com/browse/CRW-2202
https://github.com/eclipse/che/issues/19869
Run minishift 3.11 with metrica API disabled. User is unable to start any workspaces;
Chenge image to `mshaposh/che-server:nightly`. Workspaces run ok.
=> fix: workspaces must not fail on metrics roles creation when APi is disabled or unauthorized

core/che-core-db-vendor-h2/pom.xml, core/che-core-db-vendor-mysql/pom.xml, core/che-core-db-vendor-postgresql/pom.xml, core/che-core-db/pom.xml, core/commons/che-core-commons-test/pom.xml, infrastructures/kubernetes/pom.xml, multiuser/api/che-multiuser-api-organization/pom.xml, multiuser/api/che-multiuser-api-permission/pom.xml, multiuser/api/che-multiuser-api-resource/pom.xml, multiuser/machine-auth/che-multiuser-machine-authentication/pom.xml, multiuser/permission/che-multiuser-permission-devfile/pom.xml, multiuser/permission/che-multiuser-permission-workspace/pom.xml, pom.xml, wsmaster/che-core-api-account/pom.xml, wsmaster/che-core-api-devfile/pom.xml, wsmaster/che-core-api-factory/pom.xml, wsmaster/che-core-api-ssh/pom.xml, wsmaster/che-core-api-system/pom.xml, wsmaster/che-core-api-user/pom.xml, wsmaster/che-core-api-workspace-activity/pom.xml, wsmaster/che-core-api-workspace/pom.xml, wsmaster/integration-tests/cascade-removal/pom.xml, wsmaster/integration-tests/mysql-tck/pom.xml, wsmaster/integration-tests/postgresql-tck/pom.xml
Used first release of`jakarta.persistence` artifact under eclipse instead of `javax.persistence`. Can't use the latest 3.x based because guice-persistence doesn't support it.
n/a
https://github.com/eclipse/che/issues/20247
1. Build and deploy
2. Start che-server
3. Start workspace
=> build: Used jakarta.persistence

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplier.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplier.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/DockerimageComponentToWorkspaceApplierTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplier.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplierTest.java, infrastructures/openshift/src/test/resources/devfile/petclinic.yaml, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/convert/component/ComponentToWorkspaceApplier.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/model/impl/ServerConfigImpl.java, wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/model/impl/ServerConfigImplTest.java
…devfile endpoint exposure is enabled
Signed-off-by: Michal Vala <mvala@redhat.com>
See analysis of https://github.com/eclipse/che/issues/20593
This PR basically checks the `CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE` and set `requireSubdomain` only for cases when it is not `single-host`.
https://github.com/eclipse/che/issues/20593
latest image `quay.io/mvala/che-server:gh20593-singleHostDevfileEndpoint`
1. deploy with `chectl server:deploy --platform openshift --cheimage=quay.io/mvala/che-server:gh20593-singleHostDevfileEndpoint --che-operator-cr-patch-yaml=patch.yml` where patch.yml is:
```
spec:
server:
customCheProperties:
CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_DEVFILE__ENDPOINT__EXPOSURE: single-host
serverExposureStrategy: single-host
```
2. Start any …
=> fix: devfile endpoint with single-host exposure

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccountTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
* Create a predefined K8s secret per nemaespace to store theia preferences.
* Include the preference secret to the `workspcae-secrets` role, to be able to manage it outside.
See https://github.com/eclipse-che/che-server/pull/172#issuecomment-953729818
https://github.com/eclipse/che/issues/20622
1. Start a workspace and open a terminal from the ide container.
2. Send an HTTP request to the kubernetes API to edit user-preferences secret: `curl -X POST <kubernetes API url>/api/v1/namespaces/<namespace name>/secrets/workspace-theia-secret --header "Content-Type: application/json-patch+json" -d '[{ "op": "add", "path": "/data", "value": { "key": "" } }]'` …
=> feat: Add a predefined configmap to store theia preferences

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactory.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/brokerphases/BrokerEnvironmentFactoryTest.java
Signed-off-by: disaster37 <linuxworkgroup@hotmail.com>
It add CPU ressource (limit and request) on container `che-plugin-artifacts-broker`. It needed when use namespace quota.
All other system container have already resources for CPU and memory ...
It set lImit and request to `300m`. I doesn't know if is the best value.
Fix issue [#20381](https://github.com/eclipse/che/issues/20381)
I have build image and tested on my k8s/rancher, aka `disaster/che-server:pr-quota`.
```
chectl server:deploy --installer=operator --domain=che-pull-request.rancher-hpd.hm.dm.ad --multiuser --chenamespace=che-pull-request --cheboottimeout=600000 --platform=k8s --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml --postgres-pvc-storage-class-name=nfs-client --workspace-pvc-storage-class-name=nfs-client -i …
```
=> fix: add CPU quota on che-plugin-artifacts-broker container

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java
Signed-off-by: Max Shaposhnik <mshaposh@redhat.com>
Backport of a fixup of the OAuth2 usernames in Git crendential secret
https://github.com/eclipse/che/issues/20790
=> [Backport] Fixup for oauth2 usernames

wsmaster/che-core-api-workspace/src/main/resources/schema/2.2.0/devfile.json, wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java, wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-quarkus.yaml
Use a new schema of the specification
https://github.com/eclipse/che/issues/20850
look at the unit test
without the new schema it doesn't work
the devfile sample is coming from https://github.com/devfile-samples/devfile-sample-code-with-quarkus repository
=> feat: bump schema of the 2.2.0 alpha specification

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/Constants.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/SshKeysConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/SshKeysConfiguratorTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
Signed-off-by: Max Shaposhnik <mshaposh@redhat.com>
Added namespace configurator for mounting existing user SSH keys into namespace during provision
Generated secret data will looks like:
[](https://github.com/eclipse/che/issues/20832)
https://github.com/eclipse/che/issues/20832
- Deploy Che with devworkspaces enabled;
- Add SSH key via Swagger API (since SSH plugin in Theia is disabled on DVW mode)
- Remove user namespace and refresh dashboard to force namespace provision again
- Check secret is created
=> Added namespace configurator for existing user SSH keys

infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/OpenshiftTokenInitializationFilter.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/OpenshiftTokenInitializationFilterTest.java, wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserManager.java, wsmaster/che-core-api-user/src/test/java/org/eclipse/che/api/user/server/UserManagerTest.java
fix: Do not override existed user's email with dummy on OpenShift
n/a
Fixes https://github.com/eclipse/che/issues/20922
1. Deploy che7 workspaces on openshift with Keycloak.
2. Create user with some real email
2.  Switch to devworkspacces
3.  Call `/api/user`. Original email have to stay the same.
=> fix: Do not override existed user's email with dummy on OpenShift

wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProvider.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
Signed-off-by: Max Shaposhnik <mshaposh@redhat.com>
- Added check for unexisting files if the're hosted in the public repo. In this case a `404` response returned instead of OAuth login request.
- Fixed OAuth credentials reading from file 
https://github.com/eclipse/che/issues/20994
https://github.com/eclipse/che/issues/21014
Setup Che, configure OAuth, create factory from public repo with devfile v2.0 but some missing files like 
`/.che/che-theia-plugins.yaml`. 401 was returned on this file previously, and factory failed. After fix 404 is returned, and
factory is launched successfully.
Reviewers, please comment how you tested the PR …
=> Fix behavior for unexisting files for public repositories

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/UserProfileConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/UserProfileConfiguratorTest.java
Signed-off-by: David Kwon <dakwon@redhat.com>
Adds the `controller.devfile.io/watch-secret: 'true'` label to the `user-profile` secret. This new label is needed for mounting the secret: https://github.com/devfile/devworkspace-operator/blob/d24da237bee2d2e43ac1fcdee1df34a49f96f15b/docs/additional-configuration.md#automatically-mounting-volumes-configmaps-and-secrets
Tested on CRC:
1. Deploy Che with this image: [quay.io/dkwon17/che-server:watch-secret](quay.io/dkwon17/che-server:watch-secret)
2. When starting a new workspace with a new user, the newly created `user-profile` secret should have the `controller.devfile.io/watch-secret: 'true'` label 
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-c …
=> fix: add new label to user-profile secret

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClient.java
After latest Java version upgrade in Che/CRW image (11.0.14), there is unexpected 400 responses to the GitLab API calls appeared:
```
2022-02-09 13:04:53,687[nio-8080-exec-7]  [WARN ] [.f.s.g.GitlabOAuthTokenFetcher 139]  - <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Experimentally it was discovered that it is somehow related to the HTTP/2 protocol and request headers format. 
To eliminate the errors, HTTP calls are now forced to use 1.1 protocol.
https://issues.redhat.com/browse/CRW-2739
Run Che or CRW on latest Java image and configure OAuth with `https://gitlab.cee.redhat.com/`. Factory cannot be resolved due to multiple 400-s errors. …
=> Set HttpClient  protocol to HTTP 1.1 due to sporadic errors

docs/grafana/dashboard.json
Signed-off-by: David Kwon <dakwon@redhat.com>
Re-adds the `che-master-jvm.json` Grafana dashboard from: https://github.com/eclipse-che/che-server/blob/900aa63f97f06185a64e7b82ef307e5ec06ef27a/deploy/openshift/templates/monitoring/grafana-dashboards.yaml#L6
I would like to re-add this file so that it can be referenced directly in the [Monitoring Che docs](https://www.eclipse.org/che/docs/che-7/administration-guide/monitoring-che/#_che_server_jvm_dashboard). The monitoring files seem to have been removed after [7.30.x](https://github.com/eclipse-che/che-server/tree/7.30.x/deploy/openshift/templates/monitoring).
The dashboard on Grafana 8.4.5:
https://github.com/eclipse/che/issues/21283
1. Set up Grafana and Prometheus in by applying the templates from here: …
=> feat: re-add Grafana dashboard for JVM monitoring

assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
fix: always bind AdminPermissionInitializer regardless of the auth mode
https://github.com/eclipse/che/issues/21330
image `quay.io/ibuziuk/che-server:admin`
=> fix: always bind AdminPermissionInitializer regardless of the auth mode

infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/configurator/OpenShiftStopWorkspaceRoleConfigurator.java
fix: handle the KubernetesClientException during the stop workspace role provisioning
https://github.com/eclipse/che/issues/21331
Image quay.io/ibuziuk/che-server:stop-role-catch
logs during provisioning with edit rights for user - `oc adm policy add-role-to-user edit "${USER}"`
```
022-04-12 12:26:57,183[main] [INFO ] [o.e.c.c.metrics.MetricsServer 46] - Metrics server started at port 8087 successfully
12-Apr-2022 12:26:57.814 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/user/eclipse-che/tomcat/webapps/api.war] has finished in [32,594] ms
12-Apr-2022 12:26:57.816 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/user/eclipse-che/tomcat/webapps/swagger.war]
12-Apr-2022 …
```
=> fix: handle the KubernetesClientException during the stop workspace role provisioning

wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java
Use secrets when fetching git data and initiate oAuth workflow if possible
Before, it was done only in case of private repositories
Now it will try on all public and private repositories
If there is no oAuth configured for the current SCM URL, try to fetch
with unauthenticated access
https://github.com/eclipse/che/issues/21346
- Try to import a  public project without any oAuth provider: should work as before (like a github URL)
- Setup github oAuth for example and then try to import a public project. You'll check that oAuth dialog is prompted and then we have github personal access token
Reviewers, please comment how you tested the PR …
=> feat: Always try to use oAuth token when fetching git repositories

infrastructures/kubernetes/pom.xml, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigUserDataConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigUserdataConfiguratorTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerModule.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcherTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubModule.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUserDataFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubGitUserDataFetcherTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabModule.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/GitUserData.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/GitUserDataFetcher.java
Add a workspace provisioner that checks registered git oAuth providers. When first provider found, a configmap with git user data, fetched from the corresponding git service, with mount to `/etc/gitconfig` is created.
https://github.com/eclipse/che/issues/20938
1. Deploy che to a cluster: `chectl server:deploy --platform=openshift -i=quay.io/ivinokur/che-server:next`
where `quay.io/ivinokur/che-server:next` is `che-server` image built from the PR.
2. [Configure GitHub oAth](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che)
3. Start a factory from a private GitHub repo e.g. `https://github.com/vinokurig/test-extension/tree/devfile2`
4. Check that `workspace-userdata-gitconfig` configmap is created in the user namespace:
``` …
```
=> chore: Apply git user data configmap to mount to /etc/gitconfig

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigUserDataConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigUserdataConfiguratorTest.java
There is `workspace-userdata-gitconfig-configmap` which mounts git user name and email from a registered oAuth provider. If no oAuth provider is registered get the user name and email from che user object.
fixes https://github.com/eclipse/che/issues/20937
1. Deploy che to a cluster: `chectl server:deploy --platform=openshift -i=quay.io/ivinokur/che-server:next`
where `quay.io/ivinokur/che-server:next` is `che-server` image built from the PR.
3. Start any factory
4. Check that `workspace-userdata-gitconfig` configmap with che user name and email is created in the user namespace: …
=> chore: Retrieve git user data from the user if no oAuth providers are registered

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/NoopOAuthAuthenticator.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/NoopBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketURLParserTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java
Read user namespace oauth token before checking the oAuth configuration in case when user manually added a bitbucket oAuth secret to the user namespace.
https://github.com/eclipse/che/issues/21189
1. Deploy che with `quay.io/ivinokur/che-server:next` image.
2. [Deploy bitbucket server](https://github.com/skabashnyuk/gitsrv/tree/main/bitbucket).
3. Add a secret to the user namespace:
```
kind: Secret
apiVersion: v1
metadata:
name: personal-access-token-<github/gitlab/bitbucket-server>
namespace: <namespace name>
labels:
app.kubernetes.io/component: scm-personal-access-token
app.kubernetes.io/part-of: che.eclipse.org
annotations:
che.eclipse.org/che-userid: <che user id>
che.eclipse.org/scm-personal-access-token-name: …
```
=> chore: Add an ability to manually configure bitbucket oAuth token

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties, multiuser/oidc/src/main/java/org/eclipse/che/multiuser/oidc/OIDCInfoProvider.java, multiuser/oidc/src/main/java/org/eclipse/che/multiuser/oidc/filter/OidcTokenInitializationFilter.java, multiuser/oidc/src/test/java/org/eclipse/che/multiuser/oidc/filter/OidcTokenInitializationFilterTest.java
This is a continuation of [improvements](https://github.com/eclipse/che/issues/21450) to deploy Che on Azure AKS in a way that after we taught Che to leverage `access_token` instead of `id_token` to access AKS, we need to able to configure email's claim's name (hardcoded to `email` and cannot be changed in current version) in Che-server. 
This PR adds support of `CHE_OIDC_EMAIL__CLAIM` to configure email's claim's name:
```
spec:
components:
cheServer:
extraProperties:
CHE_OIDC_EMAIL__CLAIM: unique_name
```
https://github.com/eclipse/che/issues/21515
I have just tested this change on Azure AKS integrated with Azure AD. 
Che-server image: docker.io/karatkep/che-server:21515-email-claim-configuration
CheCluster patch:
```
spec:
networking:
auth:
identityProviderURL: …
```
=> feat(oidc): email claim configuration

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java
GitHub allows to use only 60 unauthorized reqests per host. In order to avid `API rate limit exceeded` GitHub eroor,
substitute the unauthorized GitHub API request to an HTTP repository request.
https://issues.redhat.com/browse/CRW-3127
1. Deploy Che with `quay.io/ivinokur/che-server:next` image e.g. `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
2. Start any GitHub factory e.g. `https://github.com/che-samples/golang-echo-example/tree/devfile2`
see: Factory should start without any problems.
=> fix: Avoid GitHub api request without token

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java
Do not throw an exception when validating an expired oauth token, return `false` instead.
When a factory starts and oauth token is found, che-server checks the token:
* current behaiviour: if the oauth token is not valid, the validation check throws an exception and the factory creation is interrupted.
* PR behaviour: if the oauth token is not valid, the validation check returns `false` instead of an error, so token regeneration mechanism starts and the factory is created successfully.
fixes https://github.com/eclipse/che/issues/21421
1. Deploy Che with `quay.io/ivinokur/che-server:next` image e.g. `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
2. [Configure GitHub …
=> fix: Improve GitHub token validation check

wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolver.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java
Fix Gitlab API raw file request.
* Pass the file path through the `rawFileLocation` function to avoid dot cut here: https://github.com/eclipse-che/che-server/blob/7878b135f2bd454aa3f4a186d8ea8462c24338a4/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java#L134
* Encode the `.che/che-editor` subpath to meet the Gitlab raw file request requirements.
fixes https://github.com/eclipse/che/issues/21562
1. Deploy Che with the `che-server` image from the PR: `chectl server:deploy -p=openshift -i=quay.io/ivinokur/che-server:next1`
2. Configure Gitlab oAuth: https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/#applying-the-gitlab-authorized-appl …
=> fix: Fix che-editor.yaml recognition

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUserDataFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java
In order to meet the token requierments of the `vscode-github-pull-request` extension, add new token scopes when requesting a GitHub token.
https://github.com/eclipse/che/issues/21581
fixes https://github.com/eclipse/che/issues/21587
1. Deploy Che with the `che-server` image from the PR: `chectl server:deploy -p=openshift -i=quay.io/ivinokur/che-server:next1`.
2. [Configure Github oAuth](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/).
3. Create a factory with a GitHub repo e.g. `https://github.com/vinokurig/test.git`.
See: GitHub will ask you to generate a token with `"repo", "user:email", "read:user", "workflow"` scopes: …
=> chore: Add new scopes to the generate GitHub token request

infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentIntegrityValidatorTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/devfile/KubernetesComponentToWorkspaceApplierTest.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/devfile/OpenshiftComponentToWorkspaceApplierTest.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticationService.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolver.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolver.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/scm/AuthorizingFactoryParameterResolverTest.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/FileContentProvider.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/URLFileContentProvider.java, wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/convert/CommandConverterTest.java, wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileIntegrityValidatorTest.java
When processing an authentication callback request set additional error query patameter to the callback url.
How it works:
1. User creates a factory form dashboard.
2. Dasboard requests che-server factory API with no error param in the request url. See https://github.com/eclipse-che/che-dashboard/pull/599
3. Che-server create factory API parses the url for the error param. No error query param means `skipAuthentication=false`. Authentication in progress.
https://github.com/eclipse-che/che-server/blob/74eb0a333d8a4c062fcc99253d4dc3f926c866d2/wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java#L104-L106
4. GitHub shows the authentication page. If User rejects the …
=> chore: Apply authentication status in the callback url

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/security/oauth1/BitbucketServerApiClientProviderTest.java
Fix a bug where url is not resolved correctly if a server url has path segments. `URI.create(https://server-url/path-segment).resolve(/second-path)` returns `https://server-url/second-path`, so the `path-segment` is ignored. [See](https://cdivilly.wordpress.com/2014/03/11/why-trailing-slashes-on-uris-are-important/)  for more details.
Add a trailing `/` to the server url and make the rest api segments reletive to fix the problem.
=> fix: Fix url resolving in the bitbucket api client

wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/scm/AuthorizingFactoryParameterResolverTest.java
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
Fixes retrieving files from git repository when filename or directory name starts with dots.
Fixes https://github.com/eclipse/che/issues/21635, and potentially https://github.com/eclipse/che/issues/21639
Could solve  as well
1. Deploy Che with
```
chectl server:deploy -p=minikube -i=quay.io/vgulyy/che-server:test-fetching-git-files
```
2. Create a workspace with a factory
https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=eclipse/che-theia/next
3. Open Plugins view, check for installed plugins. Open terminal in editor container, check for `.vsix` files existence in `/plugins/sidecars/tools` directory.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md# …
=> fix: Allow to get files from git repository if file name starts with dot

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubUrlTest.java
Inject the `che.integration.github.disable_subdomain_isolation` env variable property to handle the [subdomain isolation](https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/enabling-subdomain-isolation) GitHub option while returning the GitHub raw file location.
https://github.com/eclipse/che/issues/21724
N/A
=> fix: Allign the GitHub raw file location Url with subdomain isolation option

wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrl.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrlTest.java
Rework the `rawFileLocation()` function to return a file url, which is available for public, without an authentication. This allows to use a factory from a public bitbucket repo without the bitbucket OAuth configuration.
https://issues.redhat.com/browse/CRW-3359
=> chore: Rework the bitbucket raw file location url

wsmaster/che-core-api-auth-gitlab/pom.xml, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
* Rework the Gitlab raw file url to return a public raw file url instead of an API request.
* Trim the `gitlabEndpoint` if it ends with `/`
fixes https://github.com/eclipse/che/issues/21696
Try to create a factory from a public Gitlab repo without the Gitlab OAuth being configured.
=> chore: Fix Gitlab raw file location url

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespace.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceTest.java, infrastructures/openshift/pom.xml, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProject.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/configurator/OpenShiftStopWorkspaceRoleConfigurator.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectTest.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/configurator/OpenShiftStopWorkspaceRoleConfiguratorTest.java
feat: Delegate only needed roles to user in his namespace
related che-operator PR: https://github.com/eclipse-che/che-operator/pull/1532
N/A
https://github.com/eclipse/che/issues/21695
1. Deploy Eclipse Che
`chectl server:deploy --platform=openshift --cheimage docker.io/abazko/che-server:21695  --che-operator-image=docker.io/abazko/operator:21695`
2. Log into Eclipse Che
3. Check `rolebindings` in a user namespace, it must contain only 2 rolebindings for the current user and it mustn't contain `admin` ClusterRoleBinding
```
oc get rolebindings -n <USER_NAMESPACE> -o custom-columns=NAME:metadata.name,ROLE:roleRef.name,SUBJECT:subjects\[0\].name  | grep <USERNAME>
NAME                                                 ROLE …
```
=> feat: Delegate only needed roles to user in his namespace

wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
Partially reverts https://github.com/eclipse-che/che-server/commit/5aa763aab38adeff1f415ae65fdd4e6efcdfced3 in order to fix the Gitlab OAuth flow.
The `rawFileUrl` method uses the API request now. If the request is passed without token it works for public repos, unlike the previous raw file request which fails for private projects, even with the Authorisation header.
https://issues.redhat.com/browse/CRW-3424
* Try to create a workspace from a public gitlab repo without an OAuth config.
* Setup the Gitlab OAuth config and try to create a workspace from a private gitlab repo.
Reviewers, …
=> fix: fix resolving Gitlab raw file location

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java
* Check if a user namespace PAT secret is present, even if the given URL doesn't match the predefined patterns:
https://github.com/eclipse-che/che-server/blob/f69dc4d9ea8c88a4f8b9c792c52de45c5036671b/wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java#L95-L98
* Fix the `getPatternMatcherByUrl()` function as `gitlabUrlPatterns.isEmpty()` condition is impossible.
* Fix the git credentials secret initialisation when a PAT secret is already present:
https://github.com/eclipse-che/che-server/blob/f69dc4d9ea8c88a4f8b9c792c52de45c5036671b/infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java#L189- …
=> fix: Fix gitlab url validation

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubCommit.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPullRequest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUser.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubApiClientTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubUrlTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
At the moment it's difficult to test the flow on custom git servers, so the functionality is temporary enabled only for github.com.
To prevent caching of raw file content, when addressing the file via https://raw.githubusercontent.com it needs to use SHA of the last commit instead of the branch name.
It gives us the unique URI on each file change.
E.g., use
```
https://raw.githubusercontent.com/vitaliy-guliy/web-nodejs-sample/ce7b7ab0aa069e0bda52eac761e2d763ae78bd71/devfile.yaml
``` 
instead of
```
https://raw.githubusercontent.com/vitaliy-guliy/web-nodejs-sample/devfilev2/devfile.yaml
```
---
When client asks the content of `devfile.yaml` in `devfilev2` branch, che-server
- gets the last commit for `devfilev2` branch using GitHub rest API …
=> Avoid caching when getting a raw file from raw.githubusercontent.com

wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketApiClient.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolver.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolver.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolverTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
bitbucket.org doesn't allow to fetch raw file content from private repositories using oAuth token any more. Override the common fetch content flow specifically for bitbucket. 
https://issues.redhat.com/browse/CRW-3584
1. Deploy che with the `quay.io/ivinokur/che-server:next`
2. Start a workspace from a private bitbucket.org repository
See: the workspace successfully starts.
=> fix: Override bitbucket content provider to use API request

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolver.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolver.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolver.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolverTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolver.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java
Currently when user rejects the oauth page for GitHub factory, Che tries to continue the factory flow without authentication (possible only for public repo). Apply the logic for the others git authentication providers.
https://issues.redhat.com/browse/CRW-3594
1. Deploy Che with `quay.io/ivinokur/che-server:next` as che-server image.
2. Start a factory from GitLab / GitLab server / Bitbucket / Bitbucket Server public repo.
3. Reject the authentication request.
See: workspace starts.
=> Retry factory authentication when user rejects git service oauth

assembly/assembly-che-tomcat/src/assembly/conf/server.xml
Tomcat allows to configure the maximum size of the request and response HTTP header. If not specified, this attribute is set to 8192 (8 KB). In order to avoid requests blocking by this limitation, tomcat configuration has been adjusted to set 32768 (32 KB).
We need it for Azure Active Directory case when auth token is quite big (more than 8KB).
More details on tomcat config: https://tomcat.apache.org/tomcat-8.0-doc/config/http.html
Request HTTP header size is limited to 32 KB (not to 8 KB by default) after this change.
https://github.com/eclipse/che/issues/21898
1. Deploy Che with `docker.io/karatkep/che-server:7.50-lh` as che-server image.
2. Call any che-server Open API, for example: GET /user. Please see screenshot above. …
=> Increase the maximum size of the request and response HTTP header to 32 KB

wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-github/pom.xml, wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticator.java, wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-github/src/test/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProviderTest.java, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-openshift/pom.xml, wsmaster/che-core-api-auth-openshift/src/main/java/org/eclipse/che/security/oauth/OpenShiftOAuthAuthenticator.java, wsmaster/che-core-api-auth-shared/src/main/java/org/eclipse/che/security/oauth/shared/dto/OAuthAuthenticatorDescriptor.java, wsmaster/che-core-api-auth/pom.xml, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java
Rework the invalidate token oauth API method to send revoke token request to the git provider. After this request Che authorisation is unsynchronised so user is asked to re apply the authentication on new factory create step.
fixes https://github.com/eclipse/che/issues/21890
1. Deploy Che with `quay.io/ivinokur/che-server:next` image.
2. Apply [GitHub oAuth flow](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/).
3. Start a factory from a GitHub repo: authorisation request is shown.
4. Go to <che-url>/swagger and find the **DELETE** `/oauth/token` method.
5. Input `github` and click `Execute`.
6. Delete current workspace and start a new factory from the GitHub repo.
See: authorisation page is …
=> Fix Delete oauth token API method

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java
Support factory from public Bitbucket-server repository without any oAuth configuration in the Che side. Add a new check that detects a Bitbucket-server url by testing it by a Bitbucket-server Api request.
https://issues.redhat.com/browse/CRW-3867
Create a factory from a public Bitbucket-server repository.
=> Apply Bitbucket server url validation by testing an API request

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java, infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
Simplification of the 'canCreateNamespace' logic, checking only single property `namespaceCreationAllowed` as part of the method.
`canCreateNamespace` has a pretty sophisticated logic. Since we do not store any relevant data in the db anymore (see https://github.com/eclipse-che/che-server/pull/398 for additional details) this resulted in the bug when the username contains special characters and can not be used as-is as a placeholder for k8s namespace / OpenShift project.
However, at this point, we probably do not need at all such checks since those were relevant only when workspaces were created and managed by che-server
https://github.com/eclipse/che/issues/21958
NOTE: should be also backported to 7.60.x for Eclipse Che 7.60.1 and Dev Spaces 3.5
image …
=> fix: Simplification of the 'canCreateNamespace' logic

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
Removing dependency on UserManager from FactoryService
N/A
Related to https://github.com/eclipse/che/issues/21374
=> refactor: Removing dependency on UserManager from FactoryService

assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java, assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties, wsmaster/che-core-api-auth-bitbucket/pom.xml, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-github/pom.xml, wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticator.java, wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-gitlab/pom.xml, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth-openshift/src/main/java/org/eclipse/che/security/oauth/OpenShiftOAuthAuthenticator.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java, wsmaster/che-core-api-factory-bitbucket-server/pom.xml, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerApiProvider.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerModule.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerApiClientProviderTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java
Apply Bitbucket Server oAuth-2 configuration for the factory flow.
Depends on https://github.com/eclipse-che/che-operator/pull/1618
https://github.com/eclipse/che/issues/21949
1. Deploy che with the test image and related modified operator image: `chectl server:deploy -p=openshift --che-operator-image=quay.io/ivinokur/che-operator:next -i=quay.io/ivinokur/che-server:next`
2. Deploy the latest Bitbucket Server instance: https://github.com/che-incubator/git-srv/blob/main/bitbucket/1_deploy_bitbucket.sh
3. Configure an `Application link` in the Bitbucket instance: https://confluence.atlassian.com/bitbucketserver0720/configure-an-incoming-link-1116282013.html:
- Use `<che url>/api/oauth/callback` as a `Redirect URL`
- Set **Admin** in the …
=> Support Bitbucket-server oAuth2 factory

make-release.sh
chore: remove ref to .ci/set_tag_version_images.sh script since it was deleted two weeks ago
Change-Id: Ie770b98d6ebd64deacb3e376f4fee0ec675135a0
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
caused by https://github.com/eclipse-che/che-server/commit/3dd20f690af6398dac3cd15b4b801cad5b1b20f7 and an incomplete cleanup after the script was removed
build error is:
```
./che-server/make-release.sh: line 232: pushd: .ci: No such file or directory
```
So this skips over the missing file.
N/A
=> chore: remove ref to .ci/set_tag_version_images.sh script since it was deleted two weeks ago

multiuser/permission/che-multiuser-permission-user/src/main/java/org/eclipse/che/multiuser/permission/user/UserServicePermissionsFilter.java, wsmaster/che-core-api-user/src/main/java/org/eclipse/che/api/user/server/UserService.java
- Deprecating `api/user` endpoints. 
- Adding extra GET `api/user/id` endpoint for easily obtaining user ID (for OpenShift cases with native OAuth enabled it is OpenShift user id)
N.B. In general, we stop using `che-server` for obtaining user-specific information. However, at this point user can not easily obtain its user id due to permission restrictions e.g.
```
oc describe user ibuziuk
Error from server (Forbidden): users.user.openshift.io "ibuziuk" is forbidden: User "ibuziuk" cannot get resource "users" in API group "user.openshift.io" at the cluster scope
```
Related to https://issues.redhat.com/browse/RHDEVDOCS-4840
image for verification: `quay.io/ibuziuk/che-server:getID`
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING …
=> refactor: Deprecating api/user endpoint. Adding exta GET api/user/id endpoint for easily obtaining user ID

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUrl.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketURLParser.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrl.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/DefaultFactoryUrl.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/RemoteFactoryUrl.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolverTest.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/DefaultFactoryUrlTest.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/FileContentProvider.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/URLFetcher.java, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/URLFileContentProvider.java, wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/URLFileContentProviderTest.java
* Add a parsing rule to detect credentials in factory URLs if it is in a format `https://<username>:<pasword>@hostname`.
* Extract the credentials from factory URLs and pass them to the devfile content request.
https://github.com/eclipse/che/issues/21998
1. Deploy che from the test image: `quay.io/ivinokur/che-server:next`
2. Create a factory from a private raw devfile url with personal access token e.g. `https://<PAT>@github.com/<path to devfile.yaml>`
=> Support Basic authentication for devfile factory URL

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsApiClient.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java
* Request for a user profile with a current token to make sure that token is valid
N/A
https://github.com/eclipse/che/issues/22051
N/A
=> fix: update the way how Azure OAuth2 token is validated

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
When Che creates a workspace from a repository URL, first we iterate and find a related git provider handler, then we gat a devfile location according to the handler rules. If we pass an unsupported git repository url we will have a default handler which will try find a devfile by the same url as the repository. In that case we will have an html content as a devfile.
We need to check the content before parsing the devfile, and throw a specific error in case if the content is not yaml.
https://github.com/eclipse/che/issues/21997
1. Deploy che via the test image: `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
For the testing purpose I disabled gitlab factory handler in the image.
2. Pass a gitlab public repo with a devfile to start a workspace e.g. …
=> Check the devfile content before creating a factory

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParser.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrl.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrlTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/DefaultFactoryUrl.java
Override the `getCredentials()` method in the `BitbucketUrl` class to intercept bitbucket URL with username e.g. `https://user@bitbucket.org/eclipse/che`. Return empty credentials for such urls.
https://issues.redhat.com/browse/CRW-4095
1. Deploy Che with the test image: `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
2. Start a workspace from a public bitbucket URL e.g. `https://ivinokur@bitbucket.org/ivinokur/public.git`
3. See: workspace starts successfully.
=> Return empty credentials from bitbucket URL with username

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java
Trim blank chars at the beginning and at the end of the token string provided by PAT
https://user-images.githubusercontent.com/1271546/226328299-ec98f86e-2d94-4dc9-b127-1e10eba783a8.mp4
part of https://github.com/eclipse/che/issues/21989
- Configure  PAT as described https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/
- Modify token by adding blank chars (like spaces or new line at the end) in the secret.
- Try to start a workspace from private repository to use created PAT  
=> fix: trim blank chars in PAT

.ci/openshift-ci/Dockerfile
* Creates the Dockerfile to configure ci-operator for implement testing pull requests in che-server on Openshift CI
* Allows the 'build root' to execute in Openshift CI, because right now there is the error:
`the build root failed after 22s with reason ManageDockerfileFailed: Failed to prepare the dockerfile for the build. `
N/A
https://github.com/eclipse/che/issues/21753
N/A
=> Create 'Dockerfile' to configure ci-operator

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessToken.java
* Withdraw the `scm-userid` annotation from the PAT secret structure.
* Rework the PAT validation to check `scm-username` instead `scm-userid`.
https://issues.redhat.com/browse/CRW-4182
1. Deploy che with the PR che-server image: `chectl server:deploy -p=openshift -i=quay.io/ivinokur/che-server:next`
2. Follow the [guide](https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) to add a PAT secret to the user namespace. Omit the `che.eclipse.org/scm-userid` annotation.
3. Try to create a workspace from a private repository.
See: workspace is started and the project is cloned.
Reviewers, please comment …
=> Withdraw scm-userid annotation in PAT secrets and use scm-username instead

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcher.java
Change the `OAUTH_PROVIDER_NAME` constant from `bitbucket` to  `bitbucket-server` in order to fix the git user data initialisation flow, when a PAT is initialised in a user namespace.
https://issues.redhat.com/browse/CRW-4339
1. Deploy che with the pr image: `chectl server:deploy -p=openshift -i=quay.io/ivinokur/che-server:next`.
2. [Apply A PAT](https://www.eclipse.org/che/docs/stable/end-user-guide/mounting-secrets/) for a bitbucket server instance.
3. Create a workspace from the bitbucket server repo.
4. Try to commit something via the vscode source control panel.
See: the action is executed successfully without any errors. …
=> Fix provider name constant in the BitbucketServerUserDataFetcher class

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java
Pass user neme instead of user id when creating a PAT secret for bitbucket-server in order to fix the generation of the`git-credentials-secret` secret which requires the user name: `https://<user name>:<token>@<host name>`.
https://github.com/eclipse/che/issues/22199
1. Deploy Che using the PR image: `chectl server:deploy -p=openshift -i=quay.io/ivinokur/che-server:next`
2. Apply [bitbucket server oAuth secret](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/)
3. Start a workspace from the bitbucket-server instance repo
See workspace starts and the project is cloned successfully. …
=> Pass user name instead of user id when creating a PAT for bitbucket-server

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubSourceStorageBuilder.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
`sparce-checkout`is no longer available from devfile 2.1, so omit the `subfolder` mechanism in order to support branch names with a `/` sign.
fixes https://github.com/eclipse/che/issues/21706
1. Create branch with a `/` sign in GitHub or GitLab repo
2. Start a workspace from the branch URl
=> Omit extracting subfolder from a workspace URL

.ci/openshift-ci/test-github-with-pat-setup-flow.sh, .ci/openshift-ci/test-gitlab-with-pat-setup-flow.sh, infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/CredentialsSecretConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/CredentialsSecretConfiguratorTest.java, infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/scm/AuthorizingFactoryParameterResolverTest.java
* On workspace start iterate user PAT secrets. If a PAT secret is not included to the `devworkspace-merged-git-credentials` secret, create a git credentials secret based on the PAT secret.
* Remove the redundant logic of creation an empty `workspace-credentials-secret` secret.
fixes https://github.com/eclipse/che/issues/22271
1. Deploy che from the PR image: `quay.io/ivinokur/che-server:22271`
2. Create a manual PAT from dashboard or from YAML: https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/
3. Start a workspace from the samples list.
See: the PAT is mounted to `/.git-credentials/credentials` file.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklis …
=> Provision git credentials secrets on workspace start

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java
Since Azure git provider do not support `username` for its user object, use `username` string as username in the git credentials file if the PAT is related to Azure Devops:
```
https://username:<token>@dev.azure.com
```
fixes https://github.com/eclipse/che/issues/22313
1. Setup an Azure DevOps PAT secret.
2. Start a workspace from a private Azure DevOps repo.
See: the workspace starts and the project is git cloned successfully.
=> Use hardcoded string as username for Azure git credentials

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketApiClient.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClient.java
Pass string to ObjectMapper instead of InputStream in order to avoid `No content to map due to end-of-input` error caused by `jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream`.
An error was discovered in our customers environment:
```
2023-07-07 11:31:31,713[nio-8080-exec-2]  [ERROR] [o.e.c.a.f.s.g.GithubApiClient 117]   - Error while parsing response body
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821)
at …
```
=> Pass string to ObjectMapper instead of InputStream

dockerfiles/che/Dockerfile
Update openjdk version from 11 to 17 in order to fix the che-server sturtup error
fixes https://github.com/eclipse/che/issues/22384
Deploy che and go to the dashboard
=> Update openjdk version from 11 to 17

wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubApiClientTest.java
Change `user.getName()` to `user.getLogin()` in the GitHub `getTokenScopes()` API request, in order to fix a bug where `NullPointer` exception is appeared when a GitHub user request returns a user with `null` in the `name` field.
fixes https://github.com/eclipse/che/issues/22413
1. In your GitHub profile clear the `Name` input and hit `Save`
2. In your user namespace remove next secrets:
- `personal-access-token-****`
- `git-credentials-secret-****`
- `devworkspace-merged-git-credentials`
3. Apply [GitHub OAuth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
4. Start a workspace from GitHub repo …
=> Use `login` instead of `name` in the GitHub scopes/username request

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParser.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParserTest.java
Do not substring `.git` while parsing Azure DevOps Urls. Azure doesn't add the `.git` suffix neither to the generated clone URLs nor to the browser repository URLs.
fixes https://github.com/eclipse/che/issues/22410
Create a workspace form a Dev Azure repository with name in format: `<repo-name>.git` e.g. https://vinokurig@dev.azure.com/vinokurig/public/_git/test.git
See: the workspace starts successfully.
=> Do not substring `.git` while parsing Azure DevOps Urls

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java
* Remove the `personalAccessTokenManager.get()` call from the OAuth API `getToken()` method. The OAuth API must not know anything about PAT secrets. It should get tokens only by requesting an SCM provider OAuth API.
* Fix validating the Bitbucket-Server PAT method by requesting user instead of requesting.
This prevents the code execution going to a recursive loop: `bitbucketServerApiClient.getPersonalAccessToken()` calls `oauthApi.getToken()` which referred to `personalAccessTokenManager.getToken()` which validated the token by calling `scmPersonalAccessTokenFetcher.getScmUsername()` -> `bitbucketServerApiClient.getPersonalAccessToken()`.
https://issues.redhat.com/browse/CRW-4351
1. Setup [bitbucket-server oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2- …
=> Do not return secret token in the Oauth API

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/scm/AuthorizingFactoryParameterResolverTest.java
* Duplicate the `git-credentials` secret creation step on create personal access token secret. Currently this step is performed on workspace provision step but in this case the PAT secret might be initialised when the provision is finished. In order to synchronise the personal access token secret and git credentials secret creation step duplicate the git credentials secret creation step after the PAT secret creation step.
* Refactor the `get(scmServerUrl)` function in the `KubernetesPersonalAccessTokenManager` class
https://issues.redhat.com/browse/CRW-4816
The issue can not be reproduced permanently
Reviewers, please comment how you …
=> Duplicate creating a git-credentials secret on token fetch

wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
A user claims that he couldn't start a workspace form GitLab repository because of the raw file location request doesn't contain the `ref` query parameter. Rework the way of generating the GitLab raw file location function to permanently add the `ref` query param.
https://issues.redhat.com/browse/CRW-4608
The initial issue is not reproducible, but we can verify that the PR doesn't break the existed logic:
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-545`
2. Start a workspace from a GitLab repository Url
=> Apply permanent `ref` query param to the GitLab raw file location request

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java
Encode the `&error_code=access_denied` query param for the callback url in order to fix the bug when the authentication request appears again if it was rejected.
**DO NOT MERGE** until https://github.com/eclipse-che/che-dashboard/pull/932 is merged
https://github.com/eclipse/che/issues/22499
fixes https://github.com/eclipse/che/issues/22539
1. Deploy che with the PR image `quay.io/eclipse/che-server:pr-568`
2. Setup the [GitHub oauth flow](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/).
3. Create a workspace from a public GitHub repository.
4. When the authentication page appears, reject the request.
See: the workspace start proceeds without fetching the token.  …
=> Encode the authentication reject error to build a proper callback url

wsmaster/che-core-api-factory-azure-devops/pom.xml, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
* Change the `getHostName()` function to `getProviderUrl()` in order to fix an error while updating an oauth token on workspace start.
* Throw `ScmUnauthorizedException` if an oAuth token is not valid, for the dashboard to open the authorisation page and update the token.
https://issues.redhat.com/browse/CRW-4957
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-597`
2. Configure GitHub (or other) oAuth2 flow.
3. Start a workspace from the GitHub repository, accept the authorisation page.
4. Go to the GitHub settings and revoke the authorisation.
5. Stop the workspace and start it again.
See: Authorisation appears and token secret is updated in the user namespace.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md …
=> Fix update token on workspace start

.github/workflows/release.yml, make-release.sh
Use gh tool instead of hub tool, that was removed from the workflow runner
https://github.com/eclipse/che/issues/22646
=> fix: che-22646 use gh instead of hub

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolverTest.java
Rework the `accept()` check in the raw devfile url resolver to respect token query parameters e.g. `https://raw.githubusercontent.com/vinokurig/private/main/devfile.yaml?token=<token>`
fixes https://github.com/eclipse/che/issues/22685
fixes https://github.com/eclipse/che/issues/22684
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-616`
2. Create a workspace from a raw devfile url located in a private GitHub repository.
see: devfile is resolved and the workspace starts successfully.
=> Expand the raw devfile url resolver pattern with token query parameter

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
Fixes a bug with broken oauth flow caused by https://github.com/eclipse-che/che-server/pull/615.
fixes https://github.com/eclipse/che/issues/22715
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-621`
2. Configure GitHub oauth flow.
3. Start a workspace from a GitHub repository.
=> Throw the API exception with authorisation URL on SCMunauthorised error

.github/workflows/build-pr-check.yml, .github/workflows/next-build.yml, build/build.sh, devfile.yaml
In order to be able to build images directly in a wotkspace container, add `BUILDER` variable to be able to execute the `build.sh` script not only with docker but with podman and buildah.
depends on https://github.com/eclipse-che/che-server/pull/573
https://github.com/eclipse/che/issues/22243
1. Start a workspace from the `che-server` repository
2. Git checkout to the `che-22243` brach
3. In the workspace terminal run `cd dockerfiles` and `.build.sh` commands
See: a new image has been built.
=> Modify the `build.sh` script to work with podman

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesAuthorisationRequestManager.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/BitbucketServerOAuthAuthenticator.java, wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth1/NoopOAuthAuthenticator.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticator.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticatorProvider.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth1/OAuthAuthenticatorTest.java
Add the list of oauth1 providers to the list of registered oauth2 providers on get registered oauth providers API request.
https://github.com/eclipse/che/issues/22723
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-624`
2. Register Bitbucket Server oauth1 provider.
3. Open `https://<che-endpoint url>/api/oauth` in a new browser tab.
See: The oauth1 provider is listed in the response JSON.
=> Return oauth1 providers on registered oauth providers list request

.ci/openshift-ci/Dockerfile, wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java, wsmaster/che-core-api-workspace/src/main/resources/schema/2.2.1/devfile.json, wsmaster/che-core-api-workspace/src/main/resources/schema/2.2.2/devfile.json
* Add missing devfile versions to the list of supported devfile versions
* Add corresponding jsons.
fixes https://github.com/eclipse/che/issues/22753
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-637`
2. Start a workspace from a repository with devfile version `2.2.2`
=> Add latest devfile versions support

.ci/openshift-ci/Dockerfile, .ci/openshift-ci/common.sh
PR works around OpenShift CI job error "DockerBuildFailed: Dockerfile build strategy has failed." after switching to new cluster profile "che-aws":
e.g. https://storage.googleapis.com/test-platform-results/pr-logs/pull/eclipse-che_che-server/643/pull-ci-eclipse-che-che-server-main-v14-bitbucket-no-pat-oauth-flow-ssh-url/1747605397394427904/build-log.txt
```
+ curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.12/openshift-client-linux.tar.gz
+ tar xvzf - -C /usr/local/bin/ oc
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
gzip: stdin: …
```
=> Move installation of oc client from Dockerfile to common.sh in OpenShift CI jobs

.ci/openshift-ci/Dockerfile, .ci/openshift-ci/common.sh
Gets rid of faulty "curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.14/openshift-client-linux.tar.gz" command in OpenShift CI jobs (it was an idea of @artaleks9).
Fixing error example: https://storage.googleapis.com/test-platform-results/pr-logs/pull/eclipse-che_che-server/634/pull-ci-eclipse-che-che-server-main-v14-bitbucket-no-pat-oauth-flow-raw-devfile-url/1747993016309649408/build-log.txt
```
+ curl https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest-4.14/openshift-client-linux.tar.gz
+ tar xvzf - -C /usr/local/bin/ oc
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0 …
```
=> Get rid of failing curl in OpenShift CI jobs

.ci/openshift-ci/Dockerfile
Fix syntax error in Dockerfile of OpenShift CI jobs 
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_che-server/634/pull-ci-eclipse-che-che-server-main-v14-bitbucket-no-pat-oauth-flow-raw-devfile-url/1748288359341494272
```
STEP 4/7: RUN yum install --assumeyes -d1 psmisc python3-pip  httpd-tools nodejs &&     pip3 install --upgrade setuptools &&     pip3 install yq &&     curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl &&     chmod +x ./kubectl &&     mv ./kubectl /usr/local/bin &&     bash <(curl -sL https://www.eclipse.org/che/chectl/) --channel=next
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line …
```
=> Fix syntax error in Dockerfile of OpenShift CI jobs

.ci/openshift-ci/common.sh, .ci/openshift-ci/pod-che-smoke-test.yaml, .ci/openshift-ci/pod-oauth-factory-test.yaml, .ci/openshift-ci/test-che-smoke-test.sh
* Adds the E2E 'Smoke' test to OpenShift CI as PR checks
* Add 'pod-che-smoke-test.yaml' component to 'openshift-ci folder'
* Create 'startSmokeTest' in 'common.sh' file
* Change container name in 'pod-oauth-factory-test.yaml' 
https://github.com/eclipse/che/issues/22047
=> Create test 'che-smoke-test' as PR checks

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java
Add isNullOrEmpty check to the BitbucketServerURLParser. The `che.integration.bitbucket.server_endpoints` named parameter can be initialised as an empty string from the corresponding environment variable.
fixes https://github.com/eclipse/che/issues/22798
1. Deploy che from the PR image: `quay.io/eclipse/che-server:pr-653`.
2. Setup [Bitbucket Cloud oauth secret](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-the-bitbucket-cloud/#applying-an-oauth-consumer-secret-for-the-bitbucket-cloud).
3. Add BitBucket Server Personal Access token.
4. Start a workspace from the Bitbucket Server repository with a devfile.
See: Workspace starts successfully.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pu …
=> Add isNullOrEmpty check to the BitbucketServerURLParser

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/GitCredentialManager.java
Set `bitbucket-*****` as a token name annotation for bitbucket token secret. This is needed to pass username instead of `oauth2` for bitbucket credentials:
https://github.com/eclipse-che/che-server/blob/7dc7a6151144b1da05ed8d6991f985db055d4440/infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java#L169-L184
This fixes the bug when a private bitbucket.org project is not cloned.
https://issues.redhat.com/browse/CRW-5952
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-662
2. [Setup bitbucket.org oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-the-bitbucket-cloud/)
3. Start a workspace from a private bitbucket.org repository.
See: the workspace starts …
=> Do not pass oauth2 as a username to Git credentials for Bitbucket

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticationService.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth1/OAuthAuthenticationServiceTest.java
The latest BItBucket Server decodes the callback url so that causes `IllegalArgumentException` error. Catch the error and decode the redirect url.
https://issues.redhat.com/browse/CRW-5663
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-663`
2. Configure [oauth1 for BitBucket Server](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-1-for-a-bitbucket-server/) instance.
3. Create a workspace from the BitBucket Server repository, accept the oauth agreement.
4. Stop the workspace and revoke the agreement from the oauth application.
5. Start the workspace and accept the agreement again.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-templa …
=> Encode redirect URL if needed on oauth1 callback request

wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java
Add revoke authorisation implementation for Gitlab.
https://github.com/eclipse/che/issues/22832
1. Deploy Che from the PR image: `quay.io/eclipse/che-server:pr-667`.
2. Apply dashboard image from the related PR: `quay.io/eclipse/che-dashboard:pr-1068`.
3. Setup [gitlab oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/) for onprem or SAAS version.
4. Start a workspace from the gitlab repository with a devfile, accept the authentication request.
5. Go to dashboard -> User Preferences -> Git Services tab and revoke the gitlab authorisation.
6. Delete the workspace.
7. Start the workspace again.
See: The authorisation request appears as it was rejected by the revoke action. …
=> Add revoke authorisation implementation for Gitlab

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolverTest.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessToken.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenParams.java
Add `che.eclipse.org/scm-provider-name` annotation to Personal Access Token secret.
https://github.com/eclipse/che/issues/22802
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-670`
2. Apply the related dashboard image: `quay.io/eclipse/che-dashboard:pr-1075`
3. Setup [GitHub oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
4. Start a workspace from a GitHub repository with a devfile, consent the authorisation request. 
5. Go to dashboard -> User Preferences -> Personal Access Tokens tab.
See: The provider value is `github`:
Reviewers, please comment how you tested the PR …
=> Add provider name annotation to PAT secret

wsmaster/che-core-api-auth-gitlab/pom.xml, wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java, wsmaster/che-core-api-auth-gitlab/src/test/java/org/eclipse/che/security/oauth/GitLabAuthenticatorTest.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java
Rework the gitlab oauth token validation check to verify if the test response has data in the returned object.
https://github.com/eclipse/che/issues/22836
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-674`
2. Configure [Gitlab oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/).
3. Start a workspace from a Gitlab repository with a devfile.
4. Go to dashboard -> User Preferences -> Git Services tab, see: the Gitlab provider is in the `authorised` state.
5. Revoke the Gitlab authorisation.
See: the authorisation state of the Gitlab provider has changed to `unauthorised`. …
=> Fix gitlab oauth token validation request

wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/NoopBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java
* Change the validation API request to get current user request. The `/rest/api/1.0/application-properties` request is irrelevant as it does not require a token.
* Pass oath token to the `getPersonalAccessToken()` API request in order to avoid circular `getToken()` request.
fixes https://github.com/eclipse/che/issues/22836
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-673`
2. Setup a Bitbucket-Server instance.
3. Configure [oauth2](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/) for the Bitbucket-Server instance.
4. Start a workspace from a repository with a devfile from the Bitbucket-Server, consent the authorisation request.
5. Go to dashboard -> User Preferences -> Git Services and see that the provider has …
=> Rework the Bitbucket Server oauth token validation

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolverTest.java
On handling raw devfile urls, request content by the url, and check if the content is a devfile. If yes treat the url as a raw devfile url.
fixes https://github.com/eclipse-che/che/issues/22937
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-683`
2. Start a workspace from a raw devfile url without `yaml` extension, e.g. `https://raw.githubusercontent.com/vinokurig/test/master/parent`
=> Support raw devfile urls without yaml extension

wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubURLParser.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java
* Return 'bitbucket-server' on oauth list request if the provider is Bitbucket server. If the provider is Bitbucket SAAS, return `bitbucket`.
* Do not test GitHub repository urls with user request if the url is a GitHub SAAS url.
https://github.com/eclipse-che/che/issues/22971
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-689`
2. Configure BitBucket server oauth2.
3. Call `<che-endpoint/api/oauth> api request, see: the provider name is `bitbucket-server`
4. Re-configure the oauth secret to BitBucket SAAS.
5. Call `<che-endpoint/api/oauth> api request, see: the provider name is `bitbucket`
Reviewers, please comment how …
=> Explicitly set Bitbucket Server provider name, fix GitHub url parser

.ci/openshift-ci/Dockerfile
* Replaces usage of http://mirrorlist.centos.org/ repo with http://vault.centos.org/ as http://mirrorlist.centos.org/ is now down that Centos 7 is EOL as of July 1st 2024.
* Without this fix, the Dockerfile fails to build on [Openshift CI](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_che-server/697/pull-ci-eclipse-che-che-server-main-v14-azure-no-pat-oauth-flow/1809377974395342848) with the error:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error" 
```
* This is more of a temporary work-around as the issue probably should be fixed in the image being used: …
=> Fix: stop using mirror.centos.org repo

pom.xml
Update com.squareup.okhttp3 maven dependency to latest: `5.0.0-alpha.14`
https://issues.redhat.com/browse/CRW-3811
N/A
=> Update com.squareup.okhttp3 maven dependency to latest

wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java, wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/Constants.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/BaseFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/BaseFactoryParameterResolverTest.java
Return devfile version 2 as a default devfile.
fixes https://github.com/eclipse-che/che/issues/23007
see https://github.com/eclipse-che/che/issues/23007
=> return devfile v2 as a default devfile

wsmaster/che-core-api-auth-azure-devops/pom.xml, wsmaster/che-core-api-auth-azure-devops/src/main/java/org/eclipse/che/security/oauth/AzureDevOpsOAuthAuthenticator.java, wsmaster/che-core-api-auth-azure-devops/src/main/java/org/eclipse/che/security/oauth/AzureDevOpsRefreshToken.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubPersonalAccessTokenFetcher.java
* Return existed token on GitHub token refresh request. GitHub Oauth tokens do not have expiration date, so no need to refresh them. Refresh token request will fail for such tokens because they do not have `expires_in ` value, see: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens#refreshing-a-user-access-token-with-a-refresh-token
* Override the `refreshToken` function for Azure DevOps. The existed refresh function from the `oauth2` package fails because Azure DevOps supports POST requests  in `application/x-www-form-urlencoded` format only.
fixes https://github.com/eclipse-che/che/issues/23028
see https://github.com/eclipse-che/che/issues/23028
Same steps are relevant for Azure DevOps
[As the author of this Pull Request I …
=> Skip refresh GitHub tokens, override refresh Azure DevOps token request

wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubURLParser.java
Fix an issue when starting a workspace using a public GitHub Server repo fails.
https://issues.redhat.com/browse/CRW-6831
Start a workspace from a public GitHub Enterprise Server repository with a devfile.
See: workspace starts
=> Apply GitHub server flag when resolving factory URL

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcherTest.java
BitBucket Server `get token()` API method does not work with PAT token. It returns unauthorised exception. Omit the BitBucket Server token skopes check because there is not other way to get the token scopes.
https://issues.redhat.com/browse/CRW-4560
1. Configure [BitBucket Server Oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/)
2. Start a workspace from the BitBucket Server repository url.
3. Apply the authorization agreement.
See workspace starts successfully, a new Personal Access Token item is created in the dashboard user preferences page.
Reviewers, please comment how you …
=> Do not validate bitbucket server token scopes

wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticator.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth1/OAuthAuthenticationService.java, wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java
Intercept the SSLHandshakeException and pass the `ssl_exception` error code when redirecting to dashboard on oAuth callback call.
https://issues.redhat.com/browse/CRW-6940
1. Deploy Che from the pull request image: `quay.io/eclipse/che-server:pr-710`
2. Apply the related dashboard image: `quay.io/eclipse/che-dashboard:pr-1171`
3. Configure oAuth for a self hosted git provider that uses self signed certificate e.g. https://gh.crw-qe.com/
4. Start a workspace from the provider's repository with a devfile.
See: A notification appears in the dashboard side:
=> Handle SSL handshake exception on SCM callback step

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/CredentialsSecretConfigurator.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/OAuthTokenSecretsConfigurator.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsApiClient.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketApiClient.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubURLParser.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubUserDataFetcher.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClient.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/ApiExceptionMapper.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AbstractGitUserDataFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/ScmPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/exception/ScmCommunicationException.java
* Throw the `ScmCommunicationException` on token validation step instead of returning invalid result.
* Propagate the `ScmCommunicationException` to the dashboard as an `ApiException`.
* Throw `ScmUnauthorizedException` on each scm api request with invalid token.
* Log error instead of throwing `RuntimeException` on workspace provision steps.
https://github.com/eclipse-che/che/issues/23076
1. Deploy Che from the PR image: `quay.io/ivinokur/che-server:che-23076` The image is built with a modification: to simulate the unreachable SCM server I changed the api endpoint url in the GitHub api client:
https://github.com/eclipse-che/che-server/blob/e04d787ed847f06faf9d18c56f0774de3cfa8b7c/wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiC …
=> Respect the ScmComunicationException on token validation step

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesAuthorisationRequestManager.java
This PR fixes the bug that causes overwriting the data section of the `workspace-preferences-configmap`.
n/a
fixes https://issues.redhat.com/browse/CRW-7179
fixes https://github.com/eclipse-che/che/issues/23154
1. Deploy the Eclipse Che (or DevSpaces) using this image: `quay.io/okurinny/che-server:next`;
2. Configure OAuth2 for the Bitbucket Cloud https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-the-bitbucket-cloud/;
3. Launch a factory using a project URL from your Bitbucket Cloud;
4. Decline the authorization prompt;
5. At this point
- the dashboard should proceed with creating the new workspace;
- the Untrusted repository modal should not appear.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING …
=> fix: apply strategic merge to workspace-preferences-configmap

wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolverTest.java
Extend the raw devfile url pattern with Bitbucket server query parameter. This fixes an issue that starting a workspace from a raw devfile url from private Bitbucket server repository shows a wrong error:
The error is about wrong oauth configuration but it is reproduced without any oauth configurations at all.
fixes https://github.com/eclipse-che/che/issues/23158
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-732`
2. Get a Raw devfile url from a **PRIVATE** Bitbucket server repository.
3. Start a workspace from the raw devfile url.
4. See: the workspace start interrupts with the error:
Reviewers, please comment how you …
=> Extend the raw devfile url pattern with Bitbucket server query parameter

wsmaster/che-core-api-factory-gitlab-common/pom.xml, wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/AbstractGitlabUserDataFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java
Fixes a bug when having gitlab and github oauth configured and GitHub oauth token is fetched, Server Exception is thrown.
fixes https://github.com/eclipse-che/che/issues/23211
1. Deploy che with the pull request image: `quay.io/eclipse/che-server:pr-733`
2. Configure [GitHub oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/).
3. Configure [Gitlab oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/).
4. Start a workspace from a GitHub repository with a devfile.
5. Go back to the dashboard page and refresh the page
6. See: Dashboard loads successfully.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist …
=> Set SAAS Gitlab url if endpint is not defined

.github/workflows/release.yml, RELEASE.md, make-release.sh
Remove Che Parent settings from release scripts, since it's an archived repository, and it's only used right now in typescript-dto module (every release uses the latest 7.15.0 version which doesn't change)
=> Remove che parent

wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProvider.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java
Improve the `isPublicRepository()` function in the `GitlabAuthorizingFileContentProvider` class to check the http response status code. The previous way with the `urlFetcher` does not work because gitlab server returns a content of an html page with credentials input instead of an error.
https://issues.redhat.com/browse/CRW-7608
1. Deploy che with the pull request image: `quay.io/eclipse/che-server:pr-741`
2. Start a workspace from a private gitlab server repository.
See: workspace start fails with the expected error message:
With this fix workspace start from a private gitlab repository will interrupt with an error if no token is …
=> Use HTTP response status code to check gitlab repositories accessibility

.ci/openshift-ci/common.sh, .ci/openshift-ci/test-gitlab-no-pat-oauth-flow.sh, .ci/openshift-ci/test-gitlab-with-pat-setup-flow.sh
Adds checking launch of workspace from gitlab repository that has .devfile.yaml
https://github.com/eclipse-che/che/issues/23255
=> Update tests checking launch of workspace from gitlab repository with a .devfile.yaml

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsApiClient.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsUserDataFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java
Handle the 302 redirect response in the azure devops api client and throw `unauthorized` exception, so the dashboard can handle it properly. Also add 401 unauthorized and 403 forbidden to the unauthorized case.
https://issues.redhat.com/browse/CRW-7941
1. Deploy che with the pull request image: `quay.io/eclipse/che-server:pr-755`.
2. Setup [Azure Devops oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-microsoft-azure-devops-services/).
3. Start a workspace from an Azure repository with a devfile, consent the authentication request.
4. See: Azure devops token is added to the user preferences tokens page.
6. Go to openshift console -> user namespace and edith the personal access token secret token, so it would become invalid.
7. Go to the dashboard …
=> Treat azure devops redirect response as unauthorized error

wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsApiClient.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsUserDataFetcher.java, wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java
Handle the 302 redirect response in the azure devops api client and throw unauthorized exception, so the dashboard can handle it properly. Also add 401 unauthorized and 403 forbidden to the unauthorized case.
cherry-pick from https://github.com/eclipse-che/che-server/pull/755
=> Treat azure devops redirect response as unauthorized error (#755)

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java
When we validate a Bitbucket Server url but neither oauth nor Personal Access Token is set up, we do a test Bitbucket Server Api request and if we get response with status 200 or 401 unauthorized, it means that the url is a Bitbucket Server url. The problem is that other unsupported git providers may also return such response on the test request. To make the check more specific, additionally test the url to match the Bitbucket Server url pattern.
fixes https://github.com/eclipse-che/che/issues/23303
see https://github.com/eclipse-che/che/issues/23303
=> Add Bitbucket Server Urls validation by pattern match

infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java, infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfigurator.java, infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/OAuthTokenSecretsConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfiguratorTest.java, wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcher.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcherTest.java, wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUserDataFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketGitUserDataFetcherTest.java, wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubURLParser.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubGitUserDataFetcherTest.java, wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java, wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/AbstractGitlabUrlParser.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AbstractGitUserDataFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/GitUserDataFetcher.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java
chore: Reduce Kubernetes namespace list request
N/A
https://github.com/eclipse-che/che/issues/23354
Deploy Che with server image from the PR, try to open a user dashboard.
=> chore: Reduce Kubernetes namespace list request

infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfigurator.java, infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfiguratorTest.java
Check the `workspace-userdata-gitconfig-configmap` configmap if it contains gitconfig with username and email and the data is not empty. Only then, try to fetch username and email from a git provider.
fixes https://github.com/eclipse-che/che/issues/23376
N/A
=> Do not fetch git username and email if the gitconfig configmap contains the data

wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubGitUserDataFetcherTest.java, wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/AbstractGitlabUserDataFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AbstractGitUserDataFetcher.java
* Fix the parameter mismatch mistake in the `AbstractGitUserDataFetcher` class. The `personalAccessTokenManager.get()` function has `scmServerUrl` as third parameter:
```java
Optional<PersonalAccessToken> get(
Subject cheUser,
@Nullable String oAuthProviderName,
@Nullable String scmServerUrl,
@Nullable String namespaceName)
throws ScmConfigurationPersistenceException, ScmCommunicationException;
```
but originally, `oAuthProviderUrl` is passed as second parameter:
```java
personalAccessTokenManager.get(cheSubject, oAuthProviderUrl, null, namespaceName);
```
* Pass the default Gitlab url (`https://gitlab.com`) if url is not defined, to the super `AbstractGitUserDataFetcher` class, when constructing the `AbstractGitlabUserDataFetcher` instance. Originally the default url was passed only to …
=> Fix parameter mismatch mistake in the AbstractGitUserDataFetcher class

wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubGitUserDataFetcherTest.java, wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/AbstractGitlabUserDataFetcher.java, wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AbstractGitUserDataFetcher.java
Fix the parameter mismatch mistake in the AbstractGitUserDataFetcher class. The personalAccessTokenManager.get() function has scmServerUrl as third parameter
backport from https://github.com/eclipse-che/che-server/pull/779
=> Fix parameter mismatch mistake in the AbstractGitUserDataFetcher class (#779)

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketApplicationProperties.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/resources/__files/bitbucket/rest/api.1.0.application-properties/response.json
Since Bitbucket Server version 8.19.14, the `/plugins/servlet/applinks/whoami` request does not return username, if PAT is used. Change the `getUser()` request to [/rest/api/1.0/application-properties](https://developer.atlassian.com/server/bitbucket/rest/v906/api-group-system-maintenance/#api-api-latest-application-properties-get) instead and extract the username from the response headers.
Example of an authorized response:
```
< HTTP/1.1 200 
< x-arequestid: @1VT0CNLx453x5668x0
< set-cookie: BITBUCKETSESSIONID=***; Max-Age=1209600; Expires=Mon, 14-Apr-2025 07:33:06 GMT; Path=/; Secure; HttpOnly
< x-auserid: 2
< x-ausername: admin
< x-asessionid: zylcf7
< cache-control: private, no-cache
< pragma: no-cache
< cache-control: no-cache, no-transform
< vary: …
```
=> Rework the Bitbucket Server getUser request

assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketApplicationProperties.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/resources/__files/bitbucket/rest/api.1.0.application-properties/response.json
Since Bitbucket Server version 8.19.14, the /plugins/servlet/applinks/whoami request does not return username, if PAT is used. Change the getUser() request to /rest/api/1.0/application-properties instead and extract the username from the response headers.
backport from https://github.com/eclipse-che/che-server/pull/790
=> Rework the Bitbucket Server getUser request (#790)

wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClient.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java, wsmaster/che-core-api-factory-bitbucket-server/src/test/resources/__files/bitbucket/rest/api/1.0/users/email-user/response.json
To get Bitbucket Server username, we read `x-ausername` header of the application properties response. The username is url encoded, so we need to encode it to have the correct username, in case it contains any special character.
https://issues.redhat.com/browse/CRW-4560
1. Deploy che from the pull request image: `quay.io/eclipse/che-server:pr-796`
2. In a Bitbucket Server instance create a user with username in a email format e.g. `user@email.com`
3. Configure [oAuth for the Bitbucket Server](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/) instance.
4. Start a workspace from the Bitbucket Server repository, consent the authorization agreement.
See: the workspace starts successfully and the project is cloned.
[As the author of this Pull …
=> Decode username when requesting Bitbucket Server user

.ci/openshift-ci/test-azure-no-pat-oauth-flow-raw-devfile-url.sh, wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolver.java, wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/RawDevfileUrlFactoryParameterResolverTest.java
Remove the RAW url pattern check from the RAW devfile url resolver, to have only the yaml content check. This is needed to revert the resolver priority to highest, and do not accept urls like `https://github.com/vinokurig/test/blob/master/path/devfile.yaml`. See https://github.com/eclipse-che/che-server/pull/793
fixes https://github.com/eclipse-che/che/issues/23433
1. Deploy che with the pull request image: `quay.io/eclipse/che-server:pr-`
2. Start a workspace from the following urls:
* Gitlab RAW devfile url: `https://gitlab.com/ivinokur/test/-/raw/main/.dfile.yaml`
* Gtilab RAW devfile API request: `<gitlab server url>/api/v4/projects/2/repository/files/devfile.yaml/raw?ref=main&private_token=<Personal Access Token>`
* Github repository devfile url: …
=> Reduce the RAW url resolver to yaml content check only

wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java, wsmaster/che-core-api-auth-bitbucket/src/test/java/org/eclipse/che/security/BitbucketOAuthAuthenticatorProviderTest.java
Encode the Bitbucket Server authentication url twice, because Bitbucket Server Decodes the callback url request.
https://issues.redhat.com/browse/CRW-8862
1. Deploy Che with the pull request image: `quay.io/eclipse/che-server:pr-808`
2. Configure [Oauth 2 for Bitbucket Server](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/) 8.19.14 or higher.
3. Logout from the Bitbucket Server account
4. Start a workspace from the Bitbucket Server repository.
5. When Che redirects to the Bitbucket Server login page, input the credentials and consent the authorization request.
See: Bitbucket Server redirects back to the Workspace load page, Bitbucket Server token is added to the user namespace. …
=> Additionally encode Bitbucket Server authentication url state

build/dockerfiles/entrypoint.sh
Align with the changes from [che-operator](https://github.com/eclipse-che/che-operator/pull/2007).
1. Deploy che from the pull request image: `quay.io/eclipse/che-server:pr-815` and related operator image: "quay.io/**ivinokur**/che-operator:next".
2. Make sure [self signed certificate](https://eclipse.dev/che/docs/stable/administration-guide/configuring-che-with-self-signed-certificate/) secret is existed in Eclipse Che namespace.
3. When the `che` pod is installed, go to the pod logs and see the message at the beginning of the log:
```
Found a custom cert. Adding it to java trust store /home/user/cacerts based on /usr/lib/jvm/jre/lib/security/cacerts
Trust this certificate? [no]:  Certificate was added to keystore
```
4. Ensure `/self-signed-cert/ca.crt` file exists, and no …
=> Read self signed certificate from file instead of env variable

wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcher.java, wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketPersonalAccessTokenFetcherTest.java
Change the name annotation prefix for Bitbucket OAuth token secrets to `oauth2-` instead of `bitbucket-`. This is needed to distinguish OAuth token secrets from Personal Access Token secrets on the dashboard side.
https://issues.redhat.com/browse/CRW-8253
1. Deploy che from the pull request image: `quay.io/eclipse/che-server:pr-`
2. Configure [oAuth for Bitbucket SAAS](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-the-bitbucket-cloud/)
3. Start a workspace from a Bitbucket SAAS repository with a devfile.
4. Go to Dashboard user preferences -> Git Services tab.
See: authorization status is active: …
=> Change the name annotation prefix for Bitbucket oauth token secrets

.github/workflows/generate-maven-sbom.yml, README.md
This PR aims to bootstrap the EF Security Team initiative of supporting projects in implementing automated SBOM generation and upload workflows, with the goal of enhancing software supply chain security.
We wanted this to seamlessly integrate with your existing release processes, so we implemented 1 workflow meant to generate an SBOM for the `che-server` product.
Currently the workflow is triggered by new releases being published. A cyclonedx maven plugin (`cyclonedx-maven-plugin`) is used to generate the SBOM, which is then uploaded as an artifact. The `store-sbom-data` reusable workflow stores additional metadata about the project and upon completion, the self service system downloads the SBOM from artifacts and uploads it to our `DependencyTrack` [instance](https://sbom.eclipse.org/), …
=> Add SBOM generation and upload workflow
