eclipse-che/che-server

- .github/workflows/build-pr-check.yml
- pom.xml
- wsmaster/integration-tests/mysql-tck/pom.xml
- wsmaster/integration-tests/mysql-tck/src/test/java/MySqlTckModule.java
- wsmaster/integration-tests/mysql-tck/src/test/resources/logback-test.xml
- wsmaster/integration-tests/postgresql-tck/pom.xml
- wsmaster/integration-tests/postgresql-tck/src/test/java/PostgreSqlTckModule.java
- Fix scm version in manifest.MF and license in integration-related code
- Fixed jgit issue during license check
n/a
n/a
> Fix scm version and license in integration related code

- core/che-core-api-model/src/main/java/org/eclipse/che/api/core/model/factory/ScmInfo.java
- wsmaster/che-core-api-factory-bitbucket-server/pom.xml
- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java
- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUrl.java
- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/BitbucketUser.java
- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-github/pom.xml
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubSourceStorageBuilder.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubUrl.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubUrlTest.java
- wsmaster/che-core-api-factory-gitlab/pom.xml
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/FactoryDevfileV2Dto.java
- wsmaster/che-core-api-factory-shared/src/main/java/org/eclipse/che/api/factory/shared/dto/ScmInfoDto.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/DefaultFactoryUrl.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/RemoteFactoryUrl.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
Provide SCM project details required for dashboard from Che-server in a separate field on the Factory.
https://github.com/eclipse/che/issues/19816
1) deploy test image `mshaposh/che-server:nightly`
2) accept factory with devfile v2.
3) make sure factory contains SCM details field
> Provide scm info in factory v2

- .github/workflows/nightly-build.yml
Fixes org.eclipse.jgit.errors.MissingObjectException: Missing commit issue
Failed build https://github.com/eclipse-che/che-server/runs/2662894926?check_suite_focus=true
- run nightly build
> Fixes org.eclipse.jgit.errors.MissingObjectException: Missing commit issue

- pom.xml
Set default release version for maven compiler plugin
n/a
Not able to run `mvn clean install -DskipTests -Dskip-validate-sources` because  Java11 settings exists only in `validation` provfile
- run `mvn clean install -DskipTests -Dskip-validate-sources`
> Set default release version for maven compiler plugin

- .github/workflows/release.yml
- make-release.sh
Minor fixes to release scripts/workflows issues caused by migration
> Fixes to release process after migration

- make-release.sh
Remove mention of e2e dockerfile from release script
> Do not build e2e image during release

- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
Fix language and links in properties files
* Fix language in properties files
* Fix broken links in properties files
* Run vale, using the configuration available in the che-docs repository.
* Check all links.
NB: it is not possible to use `htmltest` on properties files.
> docs: Fix language and links in the properties files.

- .ci/set_tag_version_images.sh
- .github/workflows/next-build.yml
- .github/workflows/nightly-build.yml
- deploy/kubernetes/helm/che/custom-charts/che-devfile-registry/values.yaml
- deploy/kubernetes/helm/che/custom-charts/che-plugin-registry/values.yaml
- deploy/kubernetes/helm/che/custom-charts/che-postgres/values.yaml
- deploy/kubernetes/helm/che/values.yaml
- dockerfiles/build.include
- make-release.sh
Add new next-build workflow to build Next images (based on last commit) with the intent to replace nightly (daily build)
Nightly build still remains, so it can be disabled later when we will be sure that we don't need it.
Also both nightly & next builds will push a short sha tag for every build, so that it remains preserved
https://github.com/eclipse/che/issues/19291
https://github.com/eclipse/che/issues/19894
> ci: Add Next & SHA tagged container builds

- .github/workflows/next-build.yml
- .github/workflows/nightly-build.yml
- dockerfiles/build.include
Fix Nightly & Next build jobs:
- add missing multiline in .yml files
- rewrite SHA tag creation
> fix: Fix nightly & next builds

- .github/workflows/release.yml
- make-release.sh
Complete the renaming of old eclipse/che repo references to eclipse-che/che-server
> Use proper che-server directory name in the release process

- wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/Constants.java
- wsmaster/che-core-api-workspace/src/main/resources/schema/2.2.0/devfile.json
- wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
- wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-simple-devfile.yaml
feat: get rid of -alpha suffix in schemaVersion for unreleased version.
As positive effect, after version is release, we avoid unneeded work:
- users won't need to update their devfile after version is released;
- we won't need to change references in our samples and code, if we rely on some feature from unreleased version, which is OK for master branch.
Dashboard is adapted in https://github.com/eclipse-che/che-dashboard/pull/271
it was agreed on DevWorkspace Cabal but no issue is created.
> feat: get rid of -alpha suffix in schemaVersion for unreleased version

- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryLinksHelper.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryLinksHelperTest.java
Prevent relative files (like che-editor.yaml, extensions.json) links creation for DEvfile v.2 factories from raw URL-s;
Fixes https://github.com/eclipse/che/issues/19985
Accept factory from devfile v.2 located at some non-repository URL (e.g. gist or equal). There must be no links to the related files (like che-editor.yaml, extensions.json)
> fix: Do not generate relative files links if factory source is a raw URL

- pom.xml
Update tomcat to the latest bugfix version 8.5.68
n/a
- deploy che-server image `quay.io/skabashn/che-server:tomcat8.5.68`
- start workspace
> fix: Update tomcat to the latest bugfix version 8.5.68

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcherTest.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java
Add support for Github PAT-based  authentication
https://github.com/eclipse/che/issues/20031
Create SCM credential secret for Github. Try to access file in private repository:
`https://che-eclipse-che.192.168.39.41.nip.io/api/scm/resolve?repository=https://github.com/mshaposhnik/test1&file=.devfile.yaml`
Before (on upstream): access failed.
After: access OK.
> feat: Add support for Github PAT-based authentication

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/GitCredentialStorageFileSecretApplier.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/KubernetesSecretAnnotationNames.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/GitCredentialStorageFileSecretApplierTest.java
Mre informative message in case of git credentials secret duplication in user namespace.
> fix: improve error message for git secrets duplication

- deploy/kubernetes/helm/che/templates/ingress.yaml
Adds nginx.org/websocket-services annotation for che ingress
N/A
https://github.com/eclipse/che/issues/19434
1. clone the project
2. cd <PROJECT_DIR>/deploy/kubernetes/helm/che
3. helm dependency update
4. chectl server:deploy --installer=helm --platform=k8s   --multiuser --domain=$(minikube ip).nip.io   --templates <PROJECT_DIR>/deploy
> fix: adds nginx.org/websocket-services annotation for che ingress

- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
Since the tests in the `infrastructure/kubernetes` module are enabled adding back the fixed secrets role test which didn't work and was removed after enabling the tests.
https://github.com/eclipse/che/issues/19837
1. cd `infrastructure/kubernetes`
2. `mvn clean install`
> Add tests for the kubernetes secrets role

- .github/workflows/next-build.yml
- .github/workflows/release.yml
Update Mattermost GH action to a working 1.1.0 version
https://github.com/eclipse/che/issues/20200
> chore: Update Mattermost GH Action to 1.1.0 version

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/secret/FileSecretApplier.java
- pom.xml
Upgrade kubernetes client to latest stable version 5.6.0
n/a
n/a
1. deploy  che-server image `quay.io/skabashn/che-server:upgradekubernetesclient5.6.0`
2. start workspace
> build: Upgrade kubernetes client to latest stable version 5.6.0

- pom.xml
Upgrade of core dependencies
- google.oauth-client 1.27.0- -> 1.31.5
- fabric8.kubernetes-client 5.6 -> 5.7
- postgresql jdbc driver 42.2.2 -> 42.2.23
- slf4j 1.7.24 -> 1.7.32
NO CQ required for this change.
Tested on minikube
openshift 4.8
- https://github.com/redhat-developer/codeready-workspaces-images/issues/84
- https://github.com/redhat-developer/codeready-workspaces-images/issues/82
- https://github.com/redhat-developer/codeready-workspaces-images/issues/83
- deploy che -server image
- start workspace
> build: Upgrade of core dependencies

- .github/workflows/next-build.yml
- make-release.sh
Remove Che Dev from CI scripts (fix next & release workflows)
> fix: remove che-dev from CI scripts

- multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/workspace/LimitsCheckingWorkspaceManager.java
Fix workspaces amount checking when creating from devfile
https://github.com/eclipse/che/issues/20187
Configure Che:
```
customCheProperties:
CHE_LIMITS_USER_WORKSPACES_COUNT: '5'
```
Before: User is able to create workspaces more than limit
After: Error is show when limit exceeded
> fix: workspaces amount limits checking

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccountTest.java
Correct prervious roles validation fixup for minikube as minikube may not allow to acccess "/" endpoint to check installed API-s.
https://github.com/eclipse/che/issues/20401
> fix: Correct prervious roles validation fixup for minikube

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/AbstractWorkspaceServiceAccount.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesWorkspaceServiceAccountTest.java
Backport of https://issues.redhat.com/browse/CRW-2202 blocker fix into release branch.
https://issues.redhat.com/browse/CRW-2202
> Backport of metrics fixup into release branch

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/OpenshiftTokenInitializationFilter.java
- infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/OpenshiftTokenInitializationFilterTest.java
Allow kube:admin user
Fixes https://github.com/eclipse/che/issues/20347
> fix: Allow kube:admin user

- .github/dependabot.yml
build: Change dependabot schedule interval to weekly
n/a
Avoid being spammed with dependabot's notifications every day.
- build && test
> build: Change dependabot schedule interval to weekly

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
Revert exception type change in prevoius PR, due to broken devworkspace operations.
https://github.com/eclipse/che/issues/20490
Before: examples failed to start with devworkspaces enabled;
After: examples are working
> Revert exception type change due to its inconvenience for scm file resolving service

- README.md
- make-release.sh
Populate the README.md with the basic information about the project, with brief overview of the structure, and CI. Also fix outdated references to CI scripts
https://github.com/eclipse/che/issues/20492
> chore: Update README.md and make-release.sh

- deploy/kubernetes/helm/che/templates/dashboard-deployment.yaml
Update dashboard deployment
N/A
https://github.com/eclipse-che/che-dashboard/pull/314
```
cd ${CHE_PROJECT}/deploy/kubernetes/helm/che
helm dependency update
chectl server:deploy --installer=helm --platform=minikube  --domain=$(minikube ip).nip.io   --templates ${CHE_PROJECT}/deploy
```
> Add CHE_HOST and CHE_URL env vars

- .github/workflows/release.yml
- typescript-dto/build.sh
- ubuntu 16.04 runners are no longer supported, so needs to update the release job runner
- ensure there is a default variable for Che parent version (currently 7.15.0) is the latest one
- in case typescript dto fails (produces wrong index.d.ts content), print it out for easier troubleshooting
> fix: Release workflow fixes

- .github/workflows/che-properties-docs-update.yml
Add workflow that will trigger che-docs workflow after changes in .properties files in main or 7.x.y branches. 
After [che-docs](https://github.com/eclipse/che-docs/pull/2129) PR will be merged, update the ID of the workflow, and merge this PR
https://github.com/eclipse/che/issues/19264
> chore: Add job for che docs variables update

- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilderTest.java
- wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/devfile/OverridePropertiesApplier.java
- wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/OverridePropertiesApplierTest.java
Allow to provide the devfileFilename in the attributes but it should not override the JSON as it's not part of the devfile directly
https://github.com/eclipse/che/issues/20607
follow up of https://github.com/eclipse-che/che-server/pull/166
Check that the test is passing and try to use /resolver API
> fix: allow to override devfileFilename

- multiuser/integration-tests/che-multiuser-cascade-removal/src/test/java/org/eclipse/che/multiuser/integration/jpa/cascaderemoval/JpaEntitiesCascadeRemovalTest.java
- wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java
- wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimesTest.java
- wsmaster/integration-tests/cascade-removal/src/test/java/org/eclipse/che/core/db/jpa/CascadeRemovalTest.java
Stopping all che-server based workspaces when DevWorkspace engine is enabled
https://youtu.be/eL-_YP6a4z4
https://github.com/eclipse/che/issues/20631
Image - `quay.io/ibuziuk/che-server:che-20631`
See screencast with details - https://youtu.be/eL-_YP6a4z4
> feat: #20631 Stopping all che-server based workspaces when DevWorkspace engine is enabled

- assembly/assembly-root-war/src/main/webapp/_app/keycloackLoader.js
- assembly/assembly-root-war/src/main/webapp/_app/loader.js
Signed-off-by: Oleksii Orel <oorel@redhat.com>
Fix IDE Loader.
fixes https://github.com/eclipse/che/issues/20783
fixes https://issues.redhat.com/browse/CRW-2465
Try to start a workspace with the following devfile
https://github.com/redhat-developer/codeready-workspaces/blob/crw-2.13-rhel-8/tech-preview-devfiles/idea/latest.yaml
A workspace should start.
> Fix ide loader

- pom.xml
Mark log4j artefacts as banned
n/a
Ensure that log4j artefacts are not used in Eclipse Che
n/a
> ci: mark log4j artefacts as banned

- pom.xml
Used tomcat 10.0.14 with latest fixes
n/a
Used tomcat 10.0.14 with latest fixes
n/a
> ci: Used tomcat 10.0.14 with latest fixes

- pom.xml
build: Upgrade logback to the latest 1.2.8
n/a
Backport from https://github.com/eclipse-che/che-server/pull/199
n/a
> build: Upgrade logback to the latest 1.2.8

- devfile.yaml
java plug-ins are using the volume `m2` but there it defines `maven` for the same path
better to use the same name for the same volume mount
https://github.com/eclipse-che/che-dashboard/pull/420#issuecomment-991081692
Open the workspace in DevWorkspace mode (using https://github.com/eclipse-che/che-dashboard/pull/420)
> chore: align volume name with plug-ins volume name

- pom.xml
Removed commons-codec as direct dependency
n/a
Removed unused dependencies to reduce the security risks. 
n/a
> build: Removed commons-codec as direct dependency

- make-release.sh
Update license headers during release, to avoid problems every new year (all changing files will have their headers automatically adjusted)
> chore: Update license headers during release

- infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java
add controller.devfile.io/watch-secret: 'true' label to workspace's git credentials
n/a
Fixes https://github.com/eclipse/che/issues/21027
- Setup Github OAuth
- Clone some private repository with factory
- You should see `git-credentials-secret-*` with `controller.devfile.io/watch-secret: 'true' ` label
> fix: add controller.devfile.io/watch-secret: 'true' label to workspace's git credentials

- assembly/assembly-wsmaster-war/pom.xml
- assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
- pom.xml
- wsmaster/che-core-api-auth-gitlab/pom.xml
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabModule.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProvider.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabUser.java
- wsmaster/che-core-api-auth-gitlab/src/test/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProviderTest.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java
- wsmaster/pom.xml
Signed-off-by: Pavol Baran <pbaran@redhat.com>
Enables OAuth flow for GitLab without Keycloak, using embededOAuthAPI.
https://github.com/eclipse/che/issues/20831
0. To setup GitLab in cluster follow https://gist.github.com/xbaran4/34e278bad2571f87c85c6c9ee1c9ca87
1. Deploy Che with DevWorkspace engine enabled and che-server image: quay.io/pbaran/che-server:gitlab8 Use chectl version next so that operator contains https://github.com/eclipse-che/che-operator/pull/1250
2. To have git credentials mounted in workspace pod, make sure to you have or update to devworkspace operator v0.10.0 or higher.
3. Follow the instruction in docs PR (https://github.com/eclipse/che-docs/pull/2202/files#diff-321a9664a608252ec41923967906b1a3e605bc576043ea0d1bab03060407df4bR19) to link GitLab and Che
4. Try to …
> GitLab OAuth authentication with embededOAuthAPI

- assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
- wsmaster/che-core-api-auth-gitlab/pom.xml
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabModule.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticator.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProvider.java
- wsmaster/che-core-api-auth-gitlab/src/main/java/org/eclipse/che/security/oauth/GitLabUser.java
- wsmaster/che-core-api-auth-gitlab/src/test/java/org/eclipse/che/security/oauth/GitLabOAuthAuthenticatorProviderTest.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabOAuthTokenFetcher.java
Fixed module che-core-api-auth-gitlab version
n/a
It is not possible to build the main branch.
- `mvn clean install`
> chore: Fixed module che-core-api-auth-gitlab version

- wsmaster/che-core-api-workspace/src/main/resources/schema/2.2.0/devfile.json
- wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/devfile/validator/DevfileSchemaValidatorTest.java
- wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-basic-nodejs.yaml
- wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-basic-python.yaml
- wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-basic-quarkus.yaml
- wsmaster/che-core-api-workspace/src/test/resources/devfile/schema_test/devfile/devfile_v2-2-0-basic-springboot.yaml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
> fix: updating devfile 2.2 schema to the latest version

- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
- wsmaster/che-core-api-auth-github/src/main/java/org/eclipse/che/security/oauth/GitHubOAuthAuthenticatorProvider.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProvider.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
- wsmaster/integration-tests/mysql-tck/pom.xml
- wsmaster/integration-tests/postgresql-tck/pom.xml
backport of Fix behavior for unexisting files for public repositories (#243)
n/a
https://issues.redhat.com/browse/CRW-2705
n/a
> Fix behavior for unexisting files for public repositories (#243)

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/UserProfileConfigurator.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/UserProfileConfiguratorTest.java
Signed-off-by: David Kwon <dakwon@redhat.com>
This PR is a backport. The original PR is here: https://github.com/eclipse-che/che-server/pull/254
> [Backport] fix: add new label to user-profile secret

- .github/workflows/try-in-web-ide.yaml
Add try in Web IDE action
n/a
https://github.com/eclipse/che/issues/20664
n/a
> ci: Add try in Web IDE action

- docs/grafana/dashboard.json
Backports https://github.com/eclipse-che/che-server/pull/283 to 7.44.x.
Please refer to https://github.com/eclipse-che/che-server/pull/283
Please refer to https://github.com/eclipse-che/che-server/pull/283
- [ TODO ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
> feat: re-add Grafana dashboard for JVM monitoring #283

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java
Update regexp to find branch/details from a Github PR link
https://github.com/eclipse/che/issues/21343
Unit tests updated
> fix: update regexp to extract the PR information

- infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java
In order to have a common credentials path for all editors, remove theia specific path segment from the `git-credentials-secret` mount path.
fixes https://github.com/eclipse/che/issues/21336
see https://github.com/eclipse/che/issues/21336
> chore: Change mount path in the git-credentials-secret

- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
This just adds a note to the `che.properties` about the importance of placing labels and keeping their format for DevWorkspaces. 
Note that this only makes sense to merge together with https://github.com/eclipse-che/che-operator/pull/1359.
N/A
eclipse/che#21327
https://github.com/eclipse-che/che-operator/pull/1359
This represents no functional change.
> fix: Add a note about the importance of the namespace labels for DevWorkspaces.

- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties
`$TITLE`
N/A
eclipse/che#21327
#286
This is just a documentation fix in `che.properties`.
> Cherry-pick #286 into 7.46.x

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigUserDataConfigurator.java
Add a `null` check when iterating configmap annotations.
https://github.com/eclipse/che/issues/20938
> fix: Fix NullPointer exception in the GitconfigUserDataConfigurator

- .ci/set_tag_version_images.sh
Adapt release scripts to removal of K8S Helm Charts directory
> fix: fix release script referring to Helm charts

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProvider.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubAuthorizingFileContentProviderTest.java
Backport from main, see https://github.com/eclipse-che/che-server/pull/325#issuecomment-1180437006
> Avoid GitHub api request without token 

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java
Backport from main, see https://github.com/eclipse-che/che-server/pull/327
> fix: Improve GitHub token validation check (#327)

- assembly/assembly-wsmaster-war/.deps/prod.md
- pom.xml
chore: bump to latest com.google.oauth-client 1.34.1 to fix CVE issue CRW-3166, CRW-3167
Change-Id: I6acfcfb7f60a5d47196c6d5a10a82dfbfdcb036a
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
N/A (or see commit message above for issue number)
N/A
> chore: bump to latest com.google.oauth-client 1.34.1 to fix CVE issue CRW-3166, CRW-3167

- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerScmFileResolver.java
- wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketScmFileResolver.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPullRequest.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolver.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubURLParser.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubScmFileResolverTest.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubUrlTest.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolver.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/ApiExceptionMapper.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/ApiExceptionMapperTest.java
* Add GitHub getPullRequest API method
* Use the API method insted of reading html content of a pull-request page when creating a factory from GitHub url.
https://issues.redhat.com/browse/CRW-3202
> chore: Add GitHub get pull request API method

- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFileContentProviderTest.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AuthorizingFileContentProvider.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/scm/AuthorizingFactoryParameterResolverTest.java
Signed-off-by: Vitaliy Gulyy <vgulyy@redhat.com>
Backport of https://github.com/eclipse-che/che-server/pull/351
Fixes retrieving files from git repository when filename or directory name starts with dots.
Fixes https://github.com/eclipse/che/issues/21635, and potentially https://github.com/eclipse/che/issues/21639
> fix: Allow to get files from git repository if file name starts with dot

- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerAuthorizingFactoryParametersResolver.java
- wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketFactoryParametersResolver.java
- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubFactoryParametersResolver.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolver.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/DefaultFactoryParameterResolver.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryParametersResolver.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/FactoryService.java
- wsmaster/che-core-api-factory/src/test/java/org/eclipse/che/api/factory/server/FactoryServiceTest.java
Fix the `/token/refresh/` factory API method by picking out the hostname from the url parameter and passing it to `personalAccessTokenManager.getAndStore(hostname)` instead of the entire factory url
https://github.com/eclipse/che/issues/21640
N/A
> chore: Align the /token/refresh/ factory API method

- pom.xml
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>
bumping kubernetes-client to the 5.12.4 version
> chore: bumping kubernetes-client to the 5.12.4 version

- assembly/assembly-wsmaster-war/pom.xml
- assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java
- assembly/assembly-wsmaster-war/src/main/resources/META-INF/persistence.xml
- assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties
- multiuser/api/che-multiuser-api-organization/src/main/java/org/eclipse/che/multiuser/organization/api/OrganizationApiModule.java
- multiuser/api/che-multiuser-api-permission/src/main/java/org/eclipse/che/multiuser/api/permission/server/PermissionsModule.java
- multiuser/api/che-multiuser-api-resource/src/main/java/org/eclipse/che/multiuser/resource/api/ResourceModule.java
- multiuser/api/che-multiuser-api-workspace-activity/src/main/java/org/eclipse/che/multiuser/api/workspace/activity/MultiUserWorkspaceActivityModule.java
- multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/deploy/KeycloakModule.java
- Decommissioning Organization, Resource, Permission, Keycloak, SSH, and Activity services
Removing the following unused and obsolete properties:
- Decommissioning Organization, Resource, Permission, Keycloak, SSH, and Activity services  
- Removing obsolete properties:
- che.limits.organization.*
- che.keycloak.cascade_user_removal_enabled
- che.keycloak.admin_username
- che.keycloak.admin_password
Related issues:
- https://github.com/eclipse/che/issues/21411
- https://github.com/eclipse/che/issues/21374
image for  verification `quay.io/ibuziuk/che-server:cleanup`
> chore: Decommissioning Organization, Resource, Permission, Keycloak, SSH, and Activity services

- .github/workflows/build-pr-check.yml
- .github/workflows/che-properties-docs-update.yml
- .github/workflows/next-build.yml
- .github/workflows/release.yml
- .github/workflows/sonar.yaml
- .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Update GitHub actions to use Node 16 and Ubuntu to latest
https://github.com/eclipse/che/issues/21763
Run GH actions to verify they still work correctly
> chore: Update GitHub actions to use Node 16 and Ubuntu to latest

- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabApiClient.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabScmFileResolverTest.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/exception/ScmCommunicationException.java
Support factory from public Gitlab-server repository without any oAuth configuration in the Che side. Add a new check that detects a Gitlab server url by testing it by a Gitlab Api request.
https://issues.redhat.com/browse/CRW-3408
Create a factory from a public Gitlab-server repository.
> Apply Gitlab server url validation by testing an API request

- wsmaster/che-core-api-factory-github/src/main/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubPersonalAccessTokenFetcherTest.java
In order to be able to use the generated github token from the workspace pod in the github CLI tool, add the necessary token scope to the list of default scopes.
https://issues.redhat.com/browse/CRW-3525
> Add "read:user" to the list of github token scopes

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactory.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactory.java
- infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
backport of https://github.com/eclipse-che/che-server/pull/431 to 7.60.x
> fix: Simplification of the 'canCreateNamespace' logic

- assembly/assembly-wsmaster-war/pom.xml
- assembly/assembly-wsmaster-war/src/main/webapp/META-INF/context.xml
- core/che-core-db-vendor-h2/pom.xml
- core/che-core-db-vendor-h2/src/main/java/org/eclipse/che/core/db/h2/jpa/eclipselink/H2SQLJndiDataSourceFactory.java
Switching to h2 data source that allows decommissioning PostgreSQL as an operand on the `che-operator` level. Once merged Database dependency will become `che-server` internal implementation detail.
Related issue - https://github.com/eclipse/che/issues/21374
Switching to h2 datasource
IMPORTANT: no data is expected to be stored in the h2 and it will be used just as a mock for obsolete che-server codebase / DTOs which can not be easily removed in one go.
image `quay.io/ibuziuk/che-server:che-21374`
Update the CR accordingly:
```
spec:
components:
cheServer:
debug: false
deployment:
containers:
- image: 'quay.io/ibuziuk/che-server:che-21374'
name: che
logLevel: INFO
```
you can now delete Postgres pod/deployment while creating / starting workspaces simultaneously without any problems.
[As …
> refactor: switching to h2 datasource 

- wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory-azure-devops/src/main/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java
fix: typo in AzureDevOpsPersonalAccessTokenFetcher
N/A
https://issues.redhat.com/browse/CRW-3927
N/A
> fix: typo in AzureDevOpsPersonalAccessTokenFetcher

- wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcher.java
- wsmaster/che-core-api-factory-azure-devops/src/main/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsPersonalAccessTokenFetcherTest.java
fix: typo in AzureDevOpsPersonalAccessTokenFetcher 
N/A
https://issues.redhat.com/browse/CRW-3927
N/A
> fix: typo in AzureDevOpsPersonalAccessTokenFetcher 

- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProvider.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrl.java
- wsmaster/che-core-api-factory-gitlab/src/main/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParser.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabAuthorizingFileContentProviderTest.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabFactoryParametersResolverTest.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlParserTest.java
feat: GitLab support nested repositories
N/A
https://github.com/eclipse/che/issues/22022
1. Create several subgroups on GitLab server
2. Try to clone a project using browser url of the repository
> feat: GitLab support nested repositories

- wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParser.java
- wsmaster/che-core-api-factory-azure-devops/src/main/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsUrl.java
- wsmaster/che-core-api-factory-azure-devops/src/test/java/org/eclipse/che/api/factory/server/azure/devops/AzureDevOpsURLParserTest.java
fix: Support Azure DevOps repository urls without project
N/A
https://github.com/eclipse/che/issues/22053
1. Deploy Eclipse Che `chectl server:deploy -p minikube --cheimage=quay.io/abazko/che-server:22053`
2. Try to start a workspace from the url like: `https://dev.azure.com/MyOrg/_git/MyRepo` (works only if project == repository name)
> fix: Support Azure DevOps repository urls without project

- .github/workflows/push-pr-number.yml
* Check launch GitHub action and Openshift CI related to update and add new files
> [DRAFT] [DO NOT MERGE] Check launch workflow and openshift ci

- README.md
Update the `Readme.md` with build and debug instructions.
https://github.com/eclipse/che/issues/15521
N/A
> Update the `Readme.md` with build and debug instructions

- .vscode/extensions.json
- devfile.yaml
Update devfile to version 2, add extensions.json
https://github.com/eclipse/che/issues/22243
Start a factory from `https://github.com/eclipse-che/che-server/compare/che-22243`
> Update devfile to version 2, add extensions.json

- .vscode/settings.json
Add some Java LS settings in order to increase performance.
> Add ./vscode/settings.json with java settings

- devfile.yaml
> chore: devfile update

- dockerfiles/che/Dockerfile
Update openjdk version from 11 to 17 in order to fix the che-server sturtup error
Cherry-picking - https://github.com/eclipse-che/che-server/pull/535
https://issues.redhat.com/browse/CRW-4792
> Update openjdk version from 11 to 17 (#535)

- pom.xml
Update `guava`, `http-client`, `squareup.okio` to the latest versions in order to fix security issues according to the `trivy` report:
```
┌───────────────────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│              Library              │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                           Title                           │
├───────────────────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────────┤
│ com.google.guava:guava (ROOT.war) │ CVE-2023-2976  │ HIGH     │ fixed  │ 31.1-jre          │ 32.0.0        │ insecure temporary directory …
```
> Update guava, http-client, squareup.okio to the latest versions

- infrastructures/infrastructure-factory/pom.xml
- infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManagerTest.java
- infrastructures/kubernetes/pom.xml
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesClientFactory.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeployments.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesObjectUtil.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInternalRuntimeTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/CheNamespaceTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesDeploymentsTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesNamespaceFactoryTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/KubernetesSecretsTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/IngressServerResolverTest.java
- infrastructures/openshift/pom.xml
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftClientFactory.java
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftWorkspaceServiceAccount.java
- infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInternalRuntimeTest.java
- infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/RouteServerResolverTest.java
- infrastructures/openshift/src/test/java/org/eclipse/che/workspace/infrastructure/openshift/project/OpenShiftProjectFactoryTest.java
- pom.xml
Update `io.fabric8.kubernetes-client` version to 6.8.1
fixes https://github.com/eclipse/che/issues/22452
Deploy Che from the PR image: `quay.io/eclipse/che-server:pr-549`
> Update io.fabric8.kubernetes-client version to latest

- core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/RuntimeExceptionMapper.java
- core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/shared/dto/ServiceError.java
In order to extend the predefined error message in the dashboard, pass original message and stack trace to a Runtime Exception DTO
N/A Technical debt.
https://github.com/eclipse/che/issues/22423
Test image: `quay.io/eclipse/che-server:pr-550`
> Pass original message and stack trace to a Runtime Exception DTO

- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUrlTest.java
Fix failing tests
https://github.com/eclipse-che/che-server/pull/545
N/A
> Fix failing unit tests

- .ci/openshift-ci/Dockerfile
Fixes the error `node is not installed` when is built the Dockerfile in Openshift-CI.
This breaks an execution of tests in PR-check
https://github.com/eclipse/che/issues/22395
> Update Dockerfile to fix an error 'node is not installed'

- .ci/openshift-ci/Dockerfile
Fixes the problem with execution command `fuser -k 8081/tcp` in the tests by updating `dnf install` in Dockerfile
https://github.com/eclipse/che/issues/22395
> Update command 'dnf install'

- .gitignore
- README.md
- pom.xml
chore: update to latest com.fasterxml.jackson 2.14.z ([CRW-4871](https://issues.redhat.com//browse/CRW-4790), #22548)
Change-Id: Iacdbd86ccc1480c8badbbc15ffe48bdb01206e44
Signed-off-by: Nick Boldt <nboldt@redhat.com>
N/A
* https://issues.redhat.com/browse/CRW-4790
* https://github.com/eclipse/che/issues/22548
N/A
> chore: update to latest com.fasterxml.jackson 2.14.z (CRW-4871, #22548)

- CONTRIBUTING.md
- README.md
Add `Contribution.md` file
depends on https://github.com/eclipse-che/che-server/pull/559
https://github.com/eclipse/che/issues/22243
N/A
> Add `CONTRIBUTING.md` file

- infrastructures/kubernetes/src/test/resources/jwtproxy-confg.yaml
- multiuser/keycloak/che-multiuser-keycloak-server/pom.xml
- multiuser/keycloak/che-multiuser-keycloak-user-remover/pom.xml
- pom.xml
- wsmaster/che-core-api-auth-bitbucket/pom.xml
- wsmaster/che-core-api-auth-github/pom.xml
- wsmaster/che-core-api-auth-gitlab/pom.xml
- wsmaster/che-core-api-auth/pom.xml
- wsmaster/che-core-api-factory-bitbucket-server/pom.xml
- wsmaster/che-core-api-factory-bitbucket/pom.xml
- wsmaster/che-core-api-factory-github/pom.xml
- wsmaster/che-core-api-factory-gitlab/pom.xml
* Update minor maven dependencies
fixes https://github.com/eclipse/che/issues/22548
N/A
> Update minor maven dependencies

- .github/workflows/release.yml
Adding hub so the release workflow can run successfully. I don't know where it came from previously, but if it was in Ubuntu by default it likely got taken out due to issues with the previous recommended install method: https://github.com/mislav/hub/issues?q=is%3Aissue+snap
Fixes failure in release workflow: https://github.com/eclipse-che/che-server/actions/runs/6563685717 
> Update release.yml to install hub

- .ci/openshift-ci/common.sh
- .ci/openshift-ci/devworkspace-test.yaml
* Fixes the problem with fail tests in PR checks on Openshift CI
eclipse/che#22649
> Fix up tests in the PR checks on Openshift CI

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/KubernetesInfraModule.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/OAuthTokenSecretsConfigurator.java
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/OpenShiftInfraModule.java
chore: Validate OAuth token secrets on namespace provisioning
N/A
https://github.com/eclipse/che/issues/22631
1. `chectl server:deploy -p minikube --cheimage=quay.io/eclipse/che-server:pr-608`
2. Configure OAuth for any git provider, for instance for GitHub.
3. Start a workspace from a private repository
4. Check token existence in `User Preferences -> Personal access tokens`
5. Go to `User Preferences -> Git Services` and rework GitHub
6. Check that there are not tokens in `User Preferences -> Personal access tokens`
> chore: Validate OAuth token secrets on namespace provisioning

- infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java
- infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java
Ignore PAT with emtpy SCM url
N/A
https://issues.redhat.com/browse/CRW-5291
N/A
> fix: Ignore PAT with emtpy SCM url

- make-release.sh
Che 7.79.0 Release has failed, because make-release.sh script uses docker commands to tag and push images that are build with `build.sh` script, that was recently changed to use `podman` by default (or other builders with BUILDER env var.
> fix: adapt to latest changes in build.sh that uses podman now

- README.md
> Update README.md - add link to status badge

- wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/GithubApiClient.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubApiClientTest.java
Fix maven build by updating corresponding license headers
N/A
N/A
> Fix license headers

- .ci/openshift-ci/Dockerfile
- README.md
PR helps to investigate OpenShift CI job error "**DockerBuildFailed: Dockerfile build strategy has failed.**" after switching to new cluster profile "che-aws":
E.g. https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_che-operator/1762/pull-ci-eclipse-che-che-operator-main-v14-che-behind-proxy/1746961290191966208
https://issues.redhat.com/browse/CRW-5370
> Get more OpenShift CI image build command logs

- .ci/openshift-ci/Dockerfile
This reverts commit dc7edf634eebb22b4eb7ea325e2da523befeaa20, and fixes openshift-client-linux.tar.gz version in OpenShift CI job Dockerfile
https://issues.redhat.com/browse/CRW-5370
> Fix openshift-client-linux.tar.gz version in OpenShift CI job Dockerfile

- wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java
- wsmaster/che-core-api-auth/src/test/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPITest.java
Some SCM providers like BItBucket Server decode the callback url so that cause `IllegalArgumentException` error. Catch the error and decode the redirect url.
https://issues.redhat.com/browse/CRW-5663
1. Deploy che with the PR image: `quay.io/eclipse/che-server:pr-654`
2. Configure oauth for a BitBucket Server instance.
3. Create a workspace from the BitBucket Server repository, accept the oauth agreement.
4. Stop the workspace and revoke the agreement from the oauth application.
5. Start the workspace and accept the agreement again.
> Encode redirect URL if needed on oauth callback request

- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java
- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java
Support BitBucket endpoint with path.
Previously it was possible to use BitBucket server endpoint in the format https://host/path.
After some changes that functionality disappeared. 
This PR fix it.
N/A
https://issues.redhat.com/browse/CRW-5762
N/A
> fix: Support BitBucket endpoint with path

- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java
- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParserTest.java
Support BitBucket endpoint with path.
Previously it was possible to use BitBucket server endpoint in the format https://host/path.
After some changes that functionality disappeared. 
This PR fix it.
N/A
https://issues.redhat.com/browse/CRW-5762
N/A
> fix: Support BitBucket endpoint with path (#665)

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
- pom.xml
Update io.fabric8.kubernetes-client to 6.10.0
https://issues.redhat.com/browse/CRW-6023
N/A
> Update io.fabric8.kubernetes-client to 6.10.0

- pom.xml
Update tomcat version to 10.1.4
https://issues.redhat.com/browse/CRW-4941
> Update tomcat version to 10.1.14

- .ci/openshift-ci/common.sh
- .ci/openshift-ci/test-azure-no-pat-oauth-flow-raw-devfile-url.sh
- .ci/openshift-ci/test-azure-no-pat-oauth-flow-ssh-url.sh
- .ci/openshift-ci/test-azure-no-pat-oauth-flow.sh
- .ci/openshift-ci/test-azure-with-pat-setup-flow.sh
- .ci/openshift-ci/test-bitbucket-no-pat-oauth-flow-raw-devfile-url.sh
- .ci/openshift-ci/test-bitbucket-no-pat-oauth-flow-ssh-url.sh
- .ci/openshift-ci/test-bitbucket-no-pat-oauth-flow.sh
- .ci/openshift-ci/test-che-smoke-test.sh
- .ci/openshift-ci/test-gitea-no-pat-oauth-flow.sh
- .ci/openshift-ci/test-gitea-with-pat-setup-flow.sh
- .ci/openshift-ci/test-github-no-pat-oauth-flow-raw-devfile-url.sh
- .ci/openshift-ci/test-github-no-pat-oauth-flow-ssh-url.sh
- .ci/openshift-ci/test-github-no-pat-oauth-flow.sh
- .ci/openshift-ci/test-github-with-pat-setup-flow.sh
- .ci/openshift-ci/test-gitlab-no-pat-oauth-flow-raw-devfile-url.sh
- .ci/openshift-ci/test-gitlab-no-pat-oauth-flow-ssh-url.sh
- .ci/openshift-ci/test-gitlab-no-pat-oauth-flow.sh
- .ci/openshift-ci/test-gitlab-with-oauth-setup-flow.sh
- .ci/openshift-ci/test-gitlab-with-pat-setup-flow.sh
* Adds info messages to git-flow tests to improve reading logs in OpenShift CI infrastructure
* Adds a style and highlighting info messages to improve readable logs in OpenShift CI infrastructure
https://github.com/eclipse/che/issues/22902
> Add info messages to git-flow tests

- pom.xml
In order to fix the `CVE-2023-6378` vulnerability, update `ch.qos.logback` maven dependency version to `1.5.6`
https://issues.redhat.com/browse/CRW-6241
N/A
> Update ch.qos.logback dependency version to latest

- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/HttpBitbucketServerApiClientTest.java
- wsmaster/che-core-api-factory-bitbucket-server/src/test/resources/__files/bitbucket/rest/access-tokens/1.0/users/ksmster/newtoken.json
Avoid using real tokens in unit test, even expired
N/A
N/A
> Avoid using real tokens in unit test, even expired

- infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesAuthorisationRequestManager.java
This is a cherry-pick of https://github.com/eclipse-che/che-server/pull/723
> fix: apply strategic merge to workspace-preferences-configmap

- .github/workflows/build-pr-check.yml
- .github/workflows/next-build.yml
- .github/workflows/release.yml
- build/build.sh
- make-release.sh
feat: Introduce multiplatform che-server image build
N/A
https://github.com/eclipse-che/che/issues/23128
1. https://quay.io/repository/eclipse/che-server?tab=tags&tag=pr-730
2. Observe image availability for different platforms 
> feat: Introduce multiplatform che-server image build

- infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java
- infrastructures/infrastructure-factory/src/test/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManagerTest.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfigurator.java
- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/OAuthTokenSecretsConfigurator.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfiguratorTest.java
- wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/EmbeddedOAuthAPI.java
- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerURLParser.java
- wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcher.java
- wsmaster/che-core-api-factory-bitbucket-server/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerUserDataFetcherTest.java
- wsmaster/che-core-api-factory-bitbucket/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketUserDataFetcher.java
- wsmaster/che-core-api-factory-bitbucket/src/test/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketGitUserDataFetcherTest.java
- wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubURLParser.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubGitUserDataFetcherTest.java
- wsmaster/che-core-api-factory-github/src/test/java/org/eclipse/che/api/factory/server/github/GithubURLParserTest.java
- wsmaster/che-core-api-factory-gitlab-common/src/main/java/org/eclipse/che/api/factory/server/gitlab/AbstractGitlabUrlParser.java
- wsmaster/che-core-api-factory-gitlab/src/test/java/org/eclipse/che/api/factory/server/gitlab/GitlabUserDataFetcherTest.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/AbstractGitUserDataFetcher.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/GitUserDataFetcher.java
- wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenManager.java
chore: Reduce the number of kubernetes request during namespace provisioning
N/A
https://github.com/eclipse-che/che/issues/23354
Deploy Eclipse Che, ensure that user dashboard is working correctly
> chore: Reduce the number of kubernetes request during namespace provisioning

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfigurator.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/configurator/GitconfigConfiguratorTest.java
Check the workspace-userdata-gitconfig-configmap configmap if it contains gitconfig with username and email and the data is not empty. Only then, try to fetch username and email from a git provider.
backport from https://github.com/eclipse-che/che-server/pull/777
> Do not fetch git username and email if the gitconfig configmap contains the data (#777)

- .github/workflows/build-pr-check.yml
- .github/workflows/next-build.yml
- .github/workflows/sonar.yaml
- .gitignore
- .mvn/develocity.xml
- .mvn/extensions.xml
- pom.xml
see https://github.com/eclipse-che/che-server/pull/767
> Added Develocity integration and enabled caching.

- README.md
See https://github.com/eclipse-che/che-server/pull/786
N/A
N/A
> Add the README Develocity section

- pom.xml
In order to fix the [CVE issues of the current tomcat version](https://mvnrepository.com/artifact/org.apache.tomcat/tomcat-catalina/10.1.14), update the apache tomcat maven dependency to `10.1.39`
https://issues.redhat.com/browse/CRW-5624
N/A
> Update the apache tomcat maven dependency to 10.1.39

- infrastructures/kubernetes/pom.xml
- infrastructures/openshift/pom.xml
- pom.xml
Update the `io.netty` transitive dependencies to `4.1.119.Final` in order to fix the [CVE-2025-24970](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-24970) vulnerability issue.
https://issues.redhat.com/browse/CRW-7969
N/A
> Fix CVE-2025-24970 vulnerability issue

- .github/workflows/build-pr-check.yml
Modify the GitHub pull request build check job to skip all docker related steps, if the job is triggered by a fork. 
fixes https://github.com/eclipse-che/che/issues/23053
See the pull request build check. This pull request is opened from a fork, so the next steps must be skipped:
- Set up QEMU
- Login to docker.io
- Login to quay.io
- Build and push images
The pull request check must succeed, the merge button must be available. 
> Skip docker related pull request check steps from a fork pr

- wsmaster/che-core-api-auth-bitbucket/src/main/java/org/eclipse/che/security/oauth/BitbucketOAuthAuthenticator.java
- wsmaster/che-core-api-auth-bitbucket/src/test/java/org/eclipse/che/security/BitbucketOAuthAuthenticatorProviderTest.java
Encode the Bitbucket Server authentication url twice, because Bitbucket Server Decodes the callback url request.
Backport from https://github.com/eclipse-che/che-server/pull/808
> Additionally encode Bitbucket Server authentication url state (#808)

- .vscode/extensions.json
> chore: Add Roo Cline extension

- infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/wsplugins/K8sContainerResolver.java
- infrastructures/kubernetes/src/test/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/log/ContainerLogWatchTest.java
- infrastructures/openshift/src/main/java/org/eclipse/che/workspace/infrastructure/openshift/multiuser/oauth/KeycloakProviderConfigFactory.java
- pom.xml
Update fabric8 Kubernetes client version to 7.4.0
fixes https://github.com/eclipse-che/che/issues/23546
N/A
> Update fabric8 Kubernetes client version to 7.4.0

- README.md
> Add contribution badge to README
